// This file exports page components for the remaining 6 verticals.
// Each vertical has its own page.tsx file in its own directory.
// This data file is imported by each.

import type { VerticalData } from './SolutionLayout';

export const THINK_TANKS_DATA: VerticalData = {
  slug: 'think-tanks', activeSlug: 'think-tanks',
  breadcrumbLabel: 'Think tanks',
  eyebrow: 'Solutions · Think tanks + nonprofits',
  heroTitle: 'Publish with<br>confidence.<br><em class="italic text-terracotta">Not with risk.</em>',
  heroBody: 'Think tank publications and advocacy positions enter the public record and stay there. A methodology weakness that a hostile commentator finds, a statistic that doesn\'t survive scrutiny from a rival institution, or a policy recommendation whose evidence base has been superseded — these become the story. Augle runs the adversarial review before publication, not after.',
  personas: [
    'Research directors reviewing pre-publication policy papers',
    'Advocacy teams stress-testing campaign evidence bases',
    'Communications leads preparing for hostile media questions',
    'Programme officers evaluating grant-funded research claims',
  ],
  panelLabel: 'Session configuration · Think tanks',
  panelRows: [
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Guardian', value: 'Policy integrity', accent: true },
    { label: 'Depth', value: 'Standard · Deep' },
    { label: 'Documents', value: 'Policy papers · research reports · briefings' },
    { label: 'SVS checks', value: 'Retraction DB · source independence · preprint status · statistical claims' },
    { label: 'Output', value: 'Finding · confidence grade · unresolved objections · audit trail' },
  ],
  problemTitle: 'The hostile critic<br>finds it after<br><em class="italic text-terracotta">you publish.</em>',
  problemBody: 'A statistic that doesn\'t survive scrutiny from a rival institution, a primary study that\'s been retracted, or a policy recommendation whose generalisation doesn\'t hold — these become the correction notice, the hostile op-ed, or the rebuttal briefing. Augle runs the adversarial review before publication.',
  problemQuestions: [
    '"Does our headline claim survive a methodological challenge from a well-resourced rival institution?"',
    '"Are any of our primary sources retracted or under challenge in the current literature?"',
    '"Does the generalisation from the research context to our policy recommendation actually hold?"',
    '"What will the hostile journalist ask us at the press briefing?"',
  ],
  problemItems: [
    { title: 'Statistical claims that don\'t survive hostile scrutiny', body: 'The Contrarian is calibrated to surface the objection a well-resourced critic at a rival institution will deploy — the methodology challenge, the statistical misrepresentation, the scope overage. Unresolved objections appear verbatim. The paper that has already survived this scrutiny is the one that gets published.' },
    { title: 'Primary studies that have been retracted or superseded', body: 'The Guardian\'s SVS cross-references every cited study against retraction databases and superseding literature. A policy recommendation built on a retracted primary study is a recommendation that becomes a correction notice.' },
    { title: 'Advocacy positions with asymmetric evidence', body: 'The Methodologist evaluates whether the evidence cited actually supports the advocacy position being made, or whether it supports a more limited claim that\'s been extended beyond its evidentiary warrant. Overstated claims invite overstated rebuttals.' },
    { title: 'Recommendations whose generalisability doesn\'t hold', body: 'The Contrarian specifically targets external validity — whether the research context (population, geography, scale, institutional setting) supports the generalisation the policy recommendation requires. Recommendations that don\'t survive this test shouldn\'t be published without a scope qualifier.' },
  ],
  useCasesTitle: 'Three sessions.<br>Three moments before launch.',
  useCasesBody: 'Each scenario is drawn from the Augle Use Case Compendium — hypothetical sessions illustrating deliberation behaviour at critical pre-publication decision points.',
  useCases: [
    {
      num: 'Use case 01 of 03 · Think tanks + nonprofits',
      name: 'The Pre-Publication Review',
      persona: 'Research Director · Health policy think tank · Pre-launch paper review',
      badge: 'Standard depth · document ingestion', badgeVariant: 'standard',
      question: '"Does our paper\'s headline claim — that universal free school meals reduce childhood obesity rates by 18% — survive methodological scrutiny, and what will critics say?"',
      highlights: [
        { agent: 'Guardian SVS', text: 'Primary source check: the 2023 study cited for the 18% figure is a preprint — flagged SVS_UNVERIFIED. Both evidence nodes that depend on it are capped at Probable. A peer-reviewed alternative exists and was published six months later.' },
        { agent: 'Methodologist', text: 'External validity: the 18% reduction is from a single-region pilot with 22 schools. The paper projects this as a national estimate. The construct validity of generalising a pilot effect to a national programme without accounting for implementation variance is a named methodological problem.' },
        { agent: 'Contrarian', text: 'Strong objection: "The 18% figure will be the correction. The preprint status will be found in 24 hours. The generalisation from 22 schools to national policy is the methodological objection a rival institution will publish within a week of your launch."' },
        { agent: 'Pragmatist', text: '(1) Replace preprint citation with the peer-reviewed 2024 version. (2) Reframe 18% as a pilot estimate, not a national projection. (3) Add one paragraph scoping the generalisation conditions. Three targeted edits, completable in one day.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'SVS flag', val: 'Primary source is preprint — peer-reviewed version exists and should replace it' },
        { key: 'Finding', val: 'Contested as headline claim — Probable with scoped generalisation and peer-reviewed source' },
        { key: 'Key objection', val: 'Single-region pilot generalised to national estimate without accounting for implementation variance' },
        { key: 'Edits needed', val: '3 targeted edits — completable in one day before launch' },
      ]},
      value: 'The paper was two days from publication. The preprint status of the primary source hadn\'t been flagged in internal review. Three targeted edits moved the paper from methodologically vulnerable to defensible — and kept the policy recommendation, which was sound, from being buried under a methodology story.',
    },
    {
      num: 'Use case 02 of 03 · Think tanks + nonprofits',
      name: 'The Advocacy Position Review',
      persona: 'Campaign Director · Criminal justice reform nonprofit · Pre-launch advocacy materials',
      badge: 'Standard depth', badgeVariant: 'standard',
      question: '"Is the evidence base for our campaign\'s central claim — that community supervision is more effective than incarceration at reducing reoffending — strong enough to withstand a hostile media cycle?"',
      highlights: [
        { agent: 'Cartographer', text: 'Settled: community supervision shows lower reoffending rates than incarceration in the specific populations studied. Contested: whether the populations studied are comparable to the general offender population. Unknown: the long-term reoffending rate beyond 24 months for the community supervision programmes cited.' },
        { agent: 'Methodologist', text: 'External validity gap: the studies cited used populations selected for community supervision — lower risk, first-time offenders, specific offence categories. The advocacy materials extend this to "all offenders." The population scope mismatch is significant.' },
        { agent: 'Contrarian', text: 'Moderate objection: "The advocacy materials claim the finding applies to \'all offenders\' when the evidence base covers \'eligible offenders\' — a subset selected for lower risk. A hostile journalist with 20 minutes and the primary studies will make this point."' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Probable for eligible low-risk offender populations — Contested when extended to all offenders' },
        { key: 'Key vulnerability', val: 'Population scope mismatch between evidence base and advocacy claim — will be found and used' },
        { key: 'Next step', val: 'Scope claim to eligible populations, prepare one-paragraph response to hostile population question' },
      ]},
      value: 'The campaign\'s evidence base was strong — for the population the research actually covered. The materials had silently extended it to all offenders. One scoping edit and a prepared FAQ for the predictable hostile question turned a vulnerability into a demonstration of research rigour.',
    },
    {
      num: 'Use case 03 of 03 · Think tanks + nonprofits',
      name: 'The Grant Application Evaluation',
      persona: 'Programme Officer · Major charitable foundation · Research grant evaluation',
      badge: 'Rapid · orientation', badgeVariant: 'standard',
      question: '"Does the research design in this grant application support the causal claims the applicant is making, and are there any methodological or integrity concerns before we shortlist?"',
      highlights: [
        { agent: 'Cartographer', text: 'Settled: the research question is important and under-studied. Contested: whether the proposed quasi-experimental design supports the causal claim the application makes. Unknown: whether the proposed instrument variable is genuinely exogenous in the proposed context.' },
        { agent: 'Guardian SVS', text: 'Two citations in the application\'s literature review are from a journal that has been flagged for systematic peer review concerns in the 2023 meta-science literature. Not retracted but integrity-flagged.' },
        { agent: 'Contrarian', text: 'Moderate objection: "The causal language in the application overstates what a quasi-experimental design can deliver — \'demonstrates\' should be \'suggests\' given the design. The journal integrity flag doesn\'t disqualify the citations but warrants a note in the evaluation record."' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Probable for the research question — Contested for the causal language given the design' },
        { key: 'SVS flag', val: 'Two citations from peer-review-integrity-flagged journal — not retracted, noted in evaluation record' },
        { key: 'Key gap', val: 'Causal language overstatement — quasi-experimental design supports association, not demonstration' },
        { key: 'Decision', val: 'Shortlist with condition: applicant to revise causal language to match design capabilities before full proposal' },
      ]},
      value: 'The application was compelling and the programme was promising. The causal claim overreach and the journal integrity flag were not visible in a standard desk review. A conditional shortlist with a scoped claim requirement protected the foundation\'s evaluation record.',
    },
  ],
  howTitle: 'Built for the research<br>publication lifecycle.',
  howSteps: [
    { n: 1, title: 'Submit your publication question and upload documents', body: 'Upload the policy paper, advocacy brief, or grant application alongside your question. The Guardian authenticates every citation against retraction databases before deliberation begins.' },
    { n: 2, title: 'The Guardian catches retracted and superseded sources', body: 'Every cited study is cross-referenced against retraction databases, superseding literature, and preprint status. A policy recommendation built on a retracted primary study is caught before publication, not after.' },
    { n: 3, title: 'The Contrarian plays the hostile critic', body: 'The Contrarian is calibrated to surface the objection a well-resourced rival institution, a hostile journalist, or an opposition researcher will deploy. Unresolved objections appear verbatim with resolution conditions — not vague concerns, but specific edits.' },
    { n: 4, title: 'You get the finding and the specific edits needed', body: 'The Pragmatist translates unresolved objections into targeted pre-publication edits — citations to replace, claims to scope, generalisations to qualify. You leave with a specific list of changes, not general uncertainty.' },
  ],
  configLabel: 'Policy integrity mode · Guardian configuration',
  configRows: [
    { key: 'Retraction check', val: 'Every cited study cross-referenced against retraction databases — retracted primary sources flagged Critical, triggering mandatory review before publication' },
    { key: 'Preprint flag', val: 'Preprint sources flagged SVS_UNVERIFIED — evidence node capped at Probable, peer-reviewed alternatives surfaced where available' },
    { key: 'Source independence', val: 'Concentration of evidence from single funder, institution, or author flagged for confirmation bias risk' },
    { key: 'Statistical claims', val: 'Statistical claims validated against original source — effect sizes, sample sizes, and statistical significance checked against cited methodology' },
    { key: 'Scope validity', val: 'Generalisation from research context to policy recommendation evaluated — population, geography, and scale mismatches flagged' },
    { key: 'Audit trail', val: 'Full session record exportable — SVS log, objection register, confidence grades, pre-publication action list' },
  ],
  whyTitle: 'What makes it different<br>from internal peer review.',
  whyCards: [
    { title: 'Runs the hostile critic before you publish', body: 'The Contrarian is calibrated to surface the objection a well-resourced critic at a rival institution, a hostile journalist, or a hostile politician\'s advisor will deploy. Unresolved objections appear verbatim with resolution conditions. The paper that goes out is the one that has already survived the worst-case scrutiny scenario.' },
    { title: 'Catches retracted and superseded sources automatically', body: 'Internal peer review doesn\'t systematically check retraction status. The Guardian\'s SVS does — every cited study, every time. A policy recommendation built on a retracted primary study is caught before it becomes a correction notice.' },
    { title: 'Grades every claim by the evidence that supports it', body: 'Not every claim in a policy paper is equally well-supported. Augle grades each one — Established, Probable, Contested, or Gap — which lets you distinguish between claims you can make confidently and ones that need a scope qualifier.' },
    { title: 'No stake in the advocacy position', body: 'Internal reviewers want the paper to succeed. Colleagues want the advocacy position to be defensible. Augle has no stake in either. It produces the finding the evidence supports — including the finding that the claim is overstated.' },
    { title: 'Specific edits, not general uncertainty', body: 'Every unresolved objection includes a resolution condition — specifically what citation, scoping language, or qualifying statement would close it. You leave with a numbered list of edits, not a vague sense that the methodology might be challenged.' },
    { title: '$0.60 per Standard session', body: 'A Standard deliberation costs $0.60. A correction notice costs credibility that takes months to rebuild. The economics of running Augle before publication are straightforward.' },
  ],
  ctaTitle: 'Publish with confidence.<br>Not with risk.',
  ctaBody: 'Join the waitlist and get one Standard session free. Run it on a real publication before your next launch.',
};

export const ENTERPRISE_DATA: VerticalData = {
  slug: 'enterprise', activeSlug: 'enterprise',
  breadcrumbLabel: 'Enterprise',
  eyebrow: 'Solutions · Enterprise',
  heroTitle: 'Test the evidence<br>before you commit<br><em class="italic text-terracotta">the capital.</em>',
  heroBody: 'Strategic decisions in large organisations are made on research that has rarely been adversarially reviewed. The market entry analysis that depends on a consultant\'s assumptions. The vendor claim that hasn\'t been triangulated against independent sources. The competitive intelligence that misses the incumbent\'s announced response. Augle stress-tests the evidence before the decision is irreversible.',
  personas: [
    'Strategy teams preparing board-level recommendations',
    'Corporate development evaluating M&A rationale',
    'Procurement teams validating vendor capability claims',
    'Competitive intelligence teams stress-testing market assessments',
  ],
  panelLabel: 'Session configuration · Enterprise',
  panelRows: [
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Guardian', value: 'Enterprise integrity', accent: true },
    { label: 'Depth', value: 'Standard · Deep' },
    { label: 'Documents', value: 'Strategy memos · market reports · vendor RFPs · analyst research' },
    { label: 'SVS checks', value: 'Market data recency · source attribution · vendor claim verification' },
    { label: 'Output', value: 'Finding · confidence grade · key risks verbatim · audit trail' },
  ],
  problemTitle: 'The board question<br>you haven\'t<br>prepared for.',
  problemBody: 'Strategic decisions made on research that hasn\'t been adversarially reviewed surface their weaknesses at the worst possible moment — in the board room, in the post-acquisition integration, or when the competitor responds exactly as their public roadmap said they would.',
  problemQuestions: [
    '"Does our market entry analysis account for the distributor partnership the incumbent announced last quarter?"',
    '"Are the vendor\'s ROI claims independently validated or are they sourced exclusively from the vendor?"',
    '"What will the board\'s skeptical member say about our competitive positioning assumptions?"',
    '"Does the M&A synergy thesis hold if the integration takes 30 months instead of 18?"',
  ],
  problemItems: [
    { title: 'Market analyses built on consultant assumptions', body: 'Internal strategy teams inherit consultant assumptions that haven\'t been independently validated. The Cartographer surfaces the specific assumption that drives the recommendation — and the Methodologist evaluates whether the evidence actually supports it.' },
    { title: 'Vendor ROI claims unsupported by independent evidence', body: 'Vendor proposals cite ROI figures from reference customers selected by the vendor. Financial integrity mode flags unattributed claims and absence of independent validation — and the Contrarian stress-tests the specific ROI figure against sector-comparable data.' },
    { title: 'Competitive intelligence with blind spots', body: 'Competitive analyses miss public information that isn\'t systematically searched — product announcements in developer blogs, partnership filings, strategic hiring signals. The Contrarian specifically targets competitive moat claims against publicly available competitor information.' },
    { title: 'The board question you haven\'t prepared for', body: "The Contrarian runs at maximum temperature to surface the board member's objection before the meeting. Unresolved objections appear verbatim with resolution conditions so you can prepare specific answers, not general defences." },
  ],
  useCasesTitle: 'Two sessions.<br>Two decisions before commitment.',
  useCasesBody: 'Each scenario is drawn from the Augle Use Case Compendium — hypothetical sessions illustrating deliberation behaviour at critical strategic decision points.',
  useCases: [
    {
      num: 'Use case 01 of 02 · Enterprise',
      name: 'The Market Entry Review',
      persona: 'VP Strategy · FTSE 100 consumer goods company · Pre-board recommendation',
      badge: 'Standard depth · document ingestion', badgeVariant: 'standard',
      question: '"Does the evidence base in our Southeast Asia market entry analysis support the recommendation to commit £120M over three years, and what are the assumptions the board will challenge?"',
      highlights: [
        { agent: 'Cartographer', text: 'Settled: the category is growing in the target markets. Contested: whether the growth rate assumption is achievable given the incumbent\'s distribution advantage. Unknown: the incumbent announced a distributor partnership last quarter that directly addresses the white space the entry strategy targets.' },
        { agent: 'Methodologist', text: 'External validity: the market share projection is built from the company\'s performance in three markets with fundamentally different distribution structures. The projection methodology doesn\'t account for distribution model differences in the target markets.' },
        { agent: 'Contrarian', text: 'Strong objection: "The incumbent\'s Q3 filing includes a distributor partnership announcement that covers two of the three target markets. The market entry analysis was completed before this announcement. The £120M recommendation is built on a competitive landscape that no longer exists."' },
        { agent: 'Pragmatist', text: 'Update competitive landscape section to incorporate Q3 filing. Commission channel partner analysis for the two affected markets before board presentation. The recommendation may survive — but it needs to address the distributor partnership explicitly.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Contested — competitive landscape has changed materially since analysis was completed' },
        { key: 'Key gap 1', val: 'Incumbent distributor partnership (Q3 filing) not incorporated — directly affects two target markets' },
        { key: 'Key gap 2', val: 'Distribution model external validity gap — projection built on structurally different markets' },
        { key: 'Next step', val: 'Update competitive section, commission channel partner analysis in two affected markets before board date' },
      ]},
      value: 'The incumbent\'s distributor announcement was public. No one on the strategy team had caught it because the analysis was already in the approval process. Finding it before the board presentation cost one week of revision. Finding it in the board room would have cost considerably more.',
    },
    {
      num: 'Use case 02 of 02 · Enterprise',
      name: 'The Vendor Evaluation',
      persona: 'Head of Procurement · Global financial services firm · Enterprise software selection',
      badge: 'Standard depth', badgeVariant: 'standard',
      question: '"Are the ROI claims in this vendor\'s enterprise proposal independently supported, and how should we weight their reference customer evidence?"',
      highlights: [
        { agent: 'Cartographer', text: 'Settled: the software category delivers measurable efficiency gains in comparable deployments. Contested: whether the 340% ROI figure in the proposal is achievable in a regulated financial services context. Unknown: the reference customers cited are all in unregulated sectors; no regulated financial services deployment is included.' },
        { agent: 'Contrarian', text: 'Strong objection: "The 340% ROI figure is sourced exclusively from the vendor\'s own case studies — no independent validation exists. The reference customers are unregulated sectors. In regulated financial services, compliance overhead materially reduces productivity gains. The ROI claim is not independently supported for this deployment context."' },
        { agent: 'Pragmatist', text: 'Request independent reference contact in regulated financial services. Commission a reference check with the vendor\'s three most comparable deployments. Negotiate contract ROI benchmarks against regulated-sector comparables, not the headline figure.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Contested — ROI figure not independently validated for regulated financial services deployment context' },
        { key: 'Key gap', val: 'All reference customers in unregulated sectors — compliance overhead not accounted for in ROI model' },
        { key: 'Next step', val: 'Request regulated-sector reference, negotiate contract benchmarks against verified comparable deployments' },
      ]},
      value: 'The vendor was eventually selected — but at a negotiated contract value that reflected the absence of independent ROI validation in the regulated sector. The procurement team had the evidence to push back on the headline figure. Without Augle, they would have accepted it as stated.',
    },
  ],
  howTitle: 'Built for the strategic<br>decision lifecycle.',
  howSteps: [
    { n: 1, title: 'Submit your decision question and upload documents', body: 'Upload the strategy memo, market analysis, or vendor proposal alongside your question. The Guardian validates market data recency, source attribution, and vendor claim independence before deliberation begins.' },
    { n: 2, title: 'The Guardian validates sources and market data', body: 'Financial integrity mode flags market data sourced from unattributed analyst research, single-source vendor claims, and forecasts presented as historical actuals. Competitive intelligence is checked against publicly available competitor information.' },
    { n: 3, title: 'The Contrarian runs the board member\'s objections', body: 'The Contrarian surfaces the competitive intelligence gap, the vendor claim weakness, and the market assumption the skeptical board member will raise. Unresolved objections appear verbatim with resolution conditions.' },
    { n: 4, title: 'You get a finding and a pre-decision action list', body: 'Unresolved objections are translated into concrete pre-decision actions — competitive analyses to update, independent validations to commission, sensitivity cases to model. You present to the board having already addressed the questions that would otherwise define the room.' },
  ],
  configLabel: 'Enterprise integrity mode · Guardian configuration',
  configRows: [
    { key: 'Market data', val: 'Market size and growth rate claims validated for source attribution and recency — single-source or unattributed estimates flagged' },
    { key: 'Vendor claims', val: 'Vendor ROI and capability claims checked for independent validation — claims sourced exclusively from the vendor flagged' },
    { key: 'Competitive intel', val: 'Competitive moat claims checked against public competitor information — product announcements, filings, strategic partnerships' },
    { key: 'Forecast vs. actual', val: 'Forward projections presented as historical performance flagged — evidence node capped at Gap' },
    { key: 'Audit trail', val: 'Full session record exportable — SVS log, board preparation items, confidence grades, action list' },
  ],
  whyTitle: 'What makes it different<br>from a management presentation.',
  whyCards: [
    { title: 'No stake in the recommendation', body: 'Internal strategy teams have invested months in the recommendation. Consultants have an interest in the engagement continuing. Vendors have an interest in winning. Augle has none of these interests — it produces the finding the evidence supports, not the finding the process has converged on.' },
    { title: 'Surfaces the board question before the meeting', body: "The Contrarian runs at maximum temperature to surface the board member's objection — the competitive gap, the assumption overreach, the vendor claim that isn't independently validated. You address it before you're in the room." },
    { title: 'An auditable evidence record for governance', body: 'The full deliberation record — evidence nodes, objections, confidence grades, Guardian flags — is exportable. For board-level decisions, the audit trail demonstrates the rigour of the analysis process.' },
    { title: 'Scales from rapid orientation to deep adversarial review', body: 'Rapid mode gives you an evidence landscape in minutes — useful for preliminary screening. Standard runs the full ensemble for significant decisions. Deep adds the flagship Contrarian for the highest-stakes commitments.' },
    { title: 'Competitive intelligence validated against public sources', body: 'The Contrarian specifically targets competitive moat claims against publicly available competitor information — product announcements in developer blogs, partnership filings, regulatory disclosures. Competitive analyses that miss public information don\'t survive this review.' },
    { title: '$0.60 per Standard session', body: 'A Standard deliberation costs $0.60. A board recommendation built on a flawed competitive analysis costs considerably more to unwind. The economics of running Augle before the board meeting are straightforward.' },
  ],
  ctaTitle: 'Test the evidence<br>before the board does.',
  ctaBody: 'Join the waitlist and get one Standard session free. Run it on a real strategic question before your next board presentation.',
};

export const HEALTHCARE_DATA: VerticalData = {
  slug: 'healthcare', activeSlug: 'healthcare',
  breadcrumbLabel: 'Healthcare + life sciences',
  eyebrow: 'Solutions · Healthcare + life sciences',
  heroTitle: 'Clinical evidence<br>reviewed before<br><em class="italic text-terracotta">it\'s consequential.</em>',
  heroBody: 'In healthcare and life sciences, the cost of an evidence failure is not a correction notice — it\'s a patient outcome, a regulatory action, or a trial result that can\'t be replicated. Augle applies adversarial scrutiny to clinical evidence, trial design, coverage decisions, and drug interaction analyses before they inform a consequential choice.',
  personas: [
    'Medical affairs teams reviewing clinical evidence for submissions',
    'Health technology assessment teams evaluating coverage decisions',
    'Clinical research teams stress-testing trial design assumptions',
    'Payer medical directors reviewing evidence for formulary decisions',
  ],
  panelLabel: 'Session configuration · Healthcare',
  panelRows: [
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Guardian', value: 'Clinical integrity', accent: true },
    { label: 'Depth', value: 'Standard · Deep' },
    { label: 'Documents', value: 'Clinical studies · systematic reviews · trial protocols · submissions' },
    { label: 'SVS checks', value: 'Retraction DB · retracted clinical studies flagged Critical · population scope · sample size thresholds' },
    { label: 'Output', value: 'Finding · confidence grade · unresolved objections · audit trail' },
  ],
  problemTitle: 'The evidence gap<br>the HTA reviewer<br>finds.',
  problemBody: 'Retracted clinical studies in evidence bases. Trial endpoints that don\'t support the submitted claim. Population scope mismatches between trial and target indication. The HTA or payer objection that surfaces during the appraisal round rather than before submission.',
  problemQuestions: [
    '"Does our HTA dossier present the clinical evidence in a way that will withstand ERG scrutiny?"',
    '"Is there a retracted study in our evidence base that we haven\'t caught?"',
    '"Does the population scope of the trial actually match the indication we\'re submitting for?"',
    '"What will the formulary committee challenge about our drug-drug interaction evidence?"',
  ],
  problemItems: [
    { title: 'Retracted clinical studies in evidence bases', body: 'Clinical integrity mode flags retracted studies at Critical severity — the highest flag level, triggering a session halt. A retracted study in a clinical evidence base is a fundamental integrity failure that should never reach an HTA committee, a formulary review, or a regulatory submission.' },
    { title: 'Trial endpoints that don\'t support the submitted claim', body: 'The Methodologist evaluates whether the trial endpoints cited — primary, secondary, exploratory — actually support the efficacy claim being made in the submission. Construct validity problems between trial endpoints and submitted claims surface here, not at the ERG.' },
    { title: 'Population scope mismatches between trial and target', body: 'The trial population and the target indication population are frequently not identical. External validity evaluation specifically checks whether the trial population is representative of the patients who will receive the treatment under the submitted indication.' },
    { title: 'The HTA or payer objection you haven\'t anticipated', body: "The Contrarian plays the ERG reviewer or formulary committee member at maximum temperature — surfacing the population scope objection, the endpoints-to-claim mismatch, and the comparative effectiveness gap that will appear in the clarification questions. You prepare for these questions before the submission, not after the clarification round begins." },
  ],
  useCasesTitle: 'Two sessions.<br>Two submissions before committee.',
  useCasesBody: 'Each scenario is drawn from the Augle Use Case Compendium — hypothetical sessions illustrating deliberation behaviour at critical pre-submission decision points.',
  useCases: [
    {
      num: 'Use case 01 of 02 · Healthcare + life sciences',
      name: 'The HTA Submission Review',
      persona: 'Medical Affairs Director · Pharmaceutical company · Pre-NICE submission',
      badge: 'Deep · flagship Contrarian', badgeVariant: 'deep',
      question: '"Does our NICE submission dossier for this oncology indication present the clinical evidence in a way that will withstand the Evidence Review Group\'s scrutiny, and what are the two or three objections we need to address?"',
      highlights: [
        { agent: 'Cartographer', text: 'Settled: the trial demonstrated statistically significant improvement in the primary endpoint (PFS). Contested: whether PFS translates to OS benefit in this indication given the heterogeneous post-progression treatment landscape. Unknown: the ERG will ask for the OS data — the dossier presents PFS as the primary endpoint without addressing the OS gap.' },
        { agent: 'Methodologist', text: 'Construct validity gap: PFS is the primary endpoint, but NICE\'s reference case for oncology submissions requires either OS or a validated surrogate endpoint with demonstrated OS correlation in this indication. The dossier does not address the surrogate endpoint validation.' },
        { agent: 'Contrarian', text: 'Strong objection (Unresolved): "The ERG\'s first clarification question will be about OS correlation. The surrogate endpoint validation for PFS in this indication has not been established in the submitted dossier. This is the appraisal committee\'s central concern — it needs to be addressed proactively, not in the clarification round."' },
        { agent: 'Pragmatist', text: 'Two pre-submission additions: (1) Surrogate endpoint validation analysis — PFS-OS correlation in this indication from published literature. (2) OS maturity update if interim data is available. Both address the ERG\'s expected clarification questions proactively.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Contested as submitted — PFS endpoint not validated as OS surrogate in this indication' },
        { key: 'Key gap 1', val: 'Surrogate endpoint validation absent — NICE reference case requires this or OS data' },
        { key: 'Key gap 2', val: 'OS maturity not addressed — ERG will request this in clarification' },
        { key: 'Next step', val: 'Add surrogate endpoint validation section and OS interim data before submission date' },
      ]},
      value: 'Both gaps were addressable — but only if they were addressed proactively in the dossier rather than reactively in the clarification round. The ERG\'s clarification questions add months to the appraisal timeline. A dossier that anticipates the questions gets a faster decision.',
    },
    {
      num: 'Use case 02 of 02 · Healthcare + life sciences',
      name: 'The Coverage Decision Review',
      persona: 'Medical Director · Large US health plan · Formulary committee preparation',
      badge: 'Standard depth', badgeVariant: 'standard',
      question: '"Is the clinical evidence presented in this prior authorisation request for a GLP-1 receptor agonist sufficient to support coverage for the requested indication, and what are the coverage criteria gaps?"',
      highlights: [
        { agent: 'Guardian SVS', text: 'Retraction check: one of the real-world evidence studies cited in the request has been retracted — publisher retraction notice from 2024, flagged Critical, session halted for review. The study supports one of the two efficacy claims in the request.' },
        { agent: 'Cartographer', text: 'Settled: GLP-1 agonists demonstrate significant weight reduction in the trials cited. Contested: whether the population in the cited trials matches the member population in the request — the trial populations excluded moderate cardiovascular risk, which the requesting member has.' },
        { agent: 'Contrarian', text: 'Moderate objection: "The population mismatch between the trial populations and the requesting member is material. The formulary committee\'s coverage criteria specifically address cardiovascular risk stratification — the request does not address the moderate CVD risk exclusion criterion."' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'SVS flag', val: 'One real-world evidence study retracted — Critical flag, session halted — supporting claim requires alternative evidence' },
        { key: 'Finding', val: 'Contested — population mismatch and retracted study require resolution before approval' },
        { key: 'Coverage gap', val: 'Moderate CVD risk exclusion criterion not addressed — formulary committee will deny on this basis' },
        { key: 'Decision', val: 'Return for additional clinical documentation addressing CVD risk and alternative RWE citation' },
      ]},
      value: 'The retracted real-world evidence study would have remained in the coverage decision record without SVS. The population mismatch would have been identified by the formulary committee — but after a coverage decision had been issued rather than before.',
    },
  ],
  howTitle: 'Built for the clinical<br>evidence lifecycle.',
  howSteps: [
    { n: 1, title: 'Submit your clinical question and upload documents', body: 'Upload the clinical evidence base, HTA dossier, or trial protocol alongside your question. Clinical integrity mode is activated — retraction status is checked for every cited study before deliberation begins.' },
    { n: 2, title: 'The Guardian flags retracted clinical studies at Critical', body: 'Clinical integrity mode cross-references every cited clinical study against retraction databases. Retracted studies trigger a Critical flag and a session halt. This cannot be waived — a retracted study in a clinical evidence base is a fundamental integrity failure.' },
    { n: 3, title: 'The Contrarian plays the ERG reviewer or formulary committee', body: 'The Contrarian surfaces the population scope objection, the endpoints-to-claim mismatch, and the comparative effectiveness gap the HTA reviewer or formulary committee will raise. Unresolved objections appear verbatim with resolution conditions.' },
    { n: 4, title: 'You get a finding and pre-submission action items', body: 'Unresolved objections are translated into concrete pre-submission additions — surrogate endpoint validations to add, population scope analyses to commission, OS data to incorporate. You submit a dossier that anticipates the clarification questions, not one that generates them.' },
  ],
  configLabel: 'Clinical integrity mode · Guardian configuration',
  configRows: [
    { key: 'Retraction check', val: 'Retracted clinical studies flagged Critical — session halted, retracted study cannot enter the evidence registry for clinical deliberations' },
    { key: 'Erratum tracking', val: 'Published errata and effect size corrections cross-referenced — corrected efficacy figures automatically updated in evidence nodes' },
    { key: 'Population scope', val: 'Trial population vs. target indication population mismatch evaluated — external validity flags raised when populations differ materially' },
    { key: 'Endpoint validity', val: 'Trial endpoints validated against submitted claim — construct validity gap between endpoint and claim flagged for ERG scrutiny' },
    { key: 'Preprint flag', val: 'Preprint clinical studies flagged SVS_UNVERIFIED — evidence node capped at Probable, peer-reviewed status required for Established grade' },
    { key: 'Audit trail', val: 'Full session record exportable — SVS retraction log, objection register, confidence grades, pre-submission action items' },
  ],
  whyTitle: 'What makes it different<br>from standard evidence review.',
  whyCards: [
    { title: 'Retracted clinical studies flagged at Critical', body: 'Clinical integrity mode flags retracted studies at Critical severity — the highest level, triggering a session halt. A retracted study in a clinical evidence base is not a data quality issue — it is a fundamental integrity failure. The Guardian\'s SVS catches it before it enters the deliberation.' },
    { title: 'Runs the HTA reviewer\'s questions in advance', body: 'The Contrarian is calibrated to surface the population scope objection, the endpoints-to-claim mismatch, and the comparative effectiveness gap the ERG or formulary committee will raise. A dossier that anticipates these questions gets a faster decision.' },
    { title: 'Produces an auditable evidence record', body: 'The full deliberation record — SVS retraction log, objection register, confidence grades — is exportable. For regulatory submissions and coverage decisions, the audit trail demonstrates the rigour of the evidence review.' },
    { title: 'Population scope evaluated, not assumed', body: 'The Methodologist specifically evaluates whether the trial population is representative of the patients who will receive the treatment under the submitted indication. Population scope mismatches between trial and target are the most common ERG clarification question — and the most addressable one.' },
    { title: 'Gap findings protect the evidence record', body: 'When the evidence is genuinely insufficient to support the submitted claim — because the relevant trial hasn\'t been done, or the population hasn\'t been studied — the finding says so explicitly. A Gap grade tells you what evidence you need before submission, not what the committee will tell you after it.' },
    { title: '$0.60 per Standard session', body: 'A Standard deliberation costs $0.60. A clarification round with NICE adds months to the appraisal timeline. A formulary committee denial requires a resubmission. The economics of running Augle before submission are straightforward.' },
  ],
  ctaTitle: 'Clinical evidence reviewed<br>before it\'s consequential.',
  ctaBody: 'Join the waitlist and get one Standard session free. Run it on a real clinical evidence question before your next submission.',
};

export const GOVERNMENT_DATA: VerticalData = {
  slug: 'government', activeSlug: 'government',
  breadcrumbLabel: 'Government',
  eyebrow: 'Solutions · Government + public sector',
  heroTitle: 'Evidence that holds<br>up to scrutiny<br><em class="italic text-terracotta">before it\'s public.</em>',
  heroBody: 'Government decisions enter the public record and are subject to scrutiny that has no deadline — parliamentary committees, NAO reviews, judicial review, FOI requests, and the sustained attention of a free press. The evidence base that underpins a public decision needs to withstand that scrutiny from the moment it\'s published. Augle applies it before publication.',
  personas: [
    'Civil servants preparing advice to ministers',
    'Policy teams developing evidence bases for major programmes',
    'Procurement officials evaluating major contract bids',
    'Heads of analysis reviewing departmental research quality',
  ],
  panelLabel: 'Session configuration · Government',
  panelRows: [
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Guardian', value: 'Policy integrity', accent: true },
    { label: 'Depth', value: 'Standard · Deep' },
    { label: 'Documents', value: 'Policy papers · ministerial briefs · impact assessments · bid documents' },
    { label: 'SVS checks', value: 'Retraction DB · statutory version · jurisdiction scope · source independence' },
    { label: 'Output', value: 'Finding · confidence grade · unresolved objections · exportable audit trail' },
  ],
  problemTitle: 'Business cases whose<br>methodology won\'t<br>survive NAO scrutiny.',
  problemBody: 'Parliamentary committees, the National Audit Office, and judicial review applicants all approach public sector evidence with the same objective: finding what didn\'t hold. The difference between the policy team that anticipates these questions and the one that hears them for the first time in committee is entirely a function of whether the adversarial review was run before publication.',
  problemQuestions: [
    '"Does our business case BCR hold under the scrutiny of the NAO\'s published methodological standards?"',
    '"What are the three questions the select committee will ask that our ministerial briefing doesn\'t currently answer?"',
    '"Are there statutory references in our impact assessment that don\'t reflect current law?"',
    '"Does our procurement business case meet the standards required to withstand challenge?"',
  ],
  problemItems: [
    { title: 'Business cases whose methodology won\'t survive NAO scrutiny', body: 'The NAO has published BCR methodology standards and has a track record of auditing specific methodological choices. The Contrarian specifically surfaces the NAO\'s methodology challenge before the business case is submitted — giving the team the opportunity to address it proactively.' },
    { title: 'Policy evidence that doesn\'t survive independent scrutiny', body: 'Select committee researchers, NAO analysts, and judicial review claimants approach policy evidence with the same adversarial intent. The Contrarian surfaces the objection they\'ll make — at maximum temperature, with the strongest possible framing.' },
    { title: 'Statutory references that are out of date or mis-scoped', body: 'Legal integrity mode checks every statutory reference against current law. Outdated statutory versions, jurisdiction mismatches, and superseded regulations are flagged before they enter a ministerial brief or impact assessment.' },
    { title: 'Procurement decisions without a defensible evidence trail', body: 'Major procurement decisions are subject to challenge by losing bidders and independent audit. The Contrarian stress-tests the evaluation methodology and the scoring rationale — surfacing challenges before the award is made, not after a claim is filed.' },
  ],
  useCasesTitle: 'Two sessions.<br>Two decisions before publication.',
  useCasesBody: 'Each scenario is drawn from the Augle Use Case Compendium — hypothetical sessions illustrating deliberation behaviour at critical pre-publication decision points.',
  useCases: [
    {
      num: 'Use case 01 of 02 · Government + public sector',
      name: 'The Business Case Review',
      persona: 'Deputy Director, Strategy · Central government department · Pre-HM Treasury submission',
      badge: 'Standard depth · document ingestion', badgeVariant: 'standard',
      question: '"Does the Full Business Case for this digital transformation programme have a BCR and cost-benefit methodology that will withstand Treasury and NAO scrutiny, and what are the two assumptions most likely to be challenged?"',
      highlights: [
        { agent: 'Cartographer', text: 'Settled: the FBC follows Green Book methodology. Contested: whether the productivity assumption (15% improvement) is supported by comparable public sector digital transformation evidence. Unknown: the NAO\'s 2023 report on public sector digital transformation found average productivity improvements of 8-11% — the FBC cites 15% without referencing the NAO\'s published benchmarks.' },
        { agent: 'Methodologist', text: 'Construct validity: the BCR of 3.2:1 depends on the 15% productivity assumption. With the NAO\'s published benchmark range of 8-11%, the BCR range is 2.1:1 to 2.6:1. The FBC presents a single-point estimate without a sensitivity analysis against published benchmarks.' },
        { agent: 'Contrarian', text: 'Strong objection (Unresolved): "The NAO\'s 2023 report is the first thing a NAO reviewer will cite. The FBC doesn\'t reference it. A BCR of 3.2:1 built on a productivity assumption that\'s above the NAO\'s published evidence range — without addressing that gap — is a BCR that doesn\'t survive the first review meeting."' },
        { agent: 'Pragmatist', text: 'Add sensitivity analysis using NAO benchmark range (8-11%). If BCR remains above 2:1 on conservative assumptions, the business case is defensible and the 15% central estimate can be retained with appropriate justification. The submission should address the NAO benchmarks, not ignore them.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Contested as submitted — productivity assumption above NAO published benchmarks without addressing the gap' },
        { key: 'Key gap 1', val: 'NAO 2023 benchmarks not referenced — Treasury reviewers will flag this immediately' },
        { key: 'Key gap 2', val: 'Single-point BCR without sensitivity analysis against published benchmark range' },
        { key: 'Next step', val: 'Add sensitivity analysis against NAO range, reference 2023 report, justify 15% central estimate with programme-specific evidence' },
      ]},
      value: 'The NAO\'s 2023 report was in the public domain. No one on the programme team had mapped it to the business case assumptions. A revised BCR of 2.6:1 on a defensible methodology is a better outcome than a challenged BCR of 3.2:1.',
    },
    {
      num: 'Use case 02 of 02 · Government + public sector',
      name: 'The Ministerial Brief Review',
      persona: 'Head of Analysis · Government department · Pre-select committee appearance',
      badge: 'Standard depth · document ingestion', badgeVariant: 'standard',
      question: '"Does the evidence base in the ministerial briefing pack for the select committee appearance on youth employment hold up, and what are the three questions the committee will ask that the brief doesn\'t currently answer?"',
      highlights: [
        { agent: 'Guardian SVS', text: 'Source check: the IFS analysis cited in the brief is from 2021 — a 2024 IFS update with materially different findings is not referenced. The committee has the 2024 update; the brief doesn\'t address it.' },
        { agent: 'Contrarian', text: 'Strong objection: "The committee researcher will have the 2024 IFS update. The brief cites the 2021 analysis as if the 2024 update doesn\'t exist. This will be the committee chair\'s opening question — and the minister will not have an answer prepared."' },
        { agent: 'Pragmatist', text: 'Add one paragraph addressing the 2024 IFS update — acknowledge the finding, explain the department\'s response, and clarify what the programme evidence shows relative to the updated analysis. This turns a vulnerability into a demonstration of departmental awareness.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'SVS flag', val: '2024 IFS update with materially different findings not referenced — committee has it' },
        { key: 'Key gap', val: 'Brief cites 2021 analysis without addressing 2024 update — committee opener' },
        { key: 'Next step', val: 'Add one paragraph addressing 2024 IFS update before committee appearance' },
      ]},
      value: 'The IFS analysis was published and the committee had it. A ministerial brief that doesn\'t acknowledge it looks like the department hasn\'t read it. A brief that addresses it proactively demonstrates the department has — and has a considered position.',
    },
  ],
  howTitle: 'Built for the public<br>sector evidence lifecycle.',
  howSteps: [
    { n: 1, title: 'Submit your policy question and upload documents', body: 'Upload the business case, ministerial brief, or impact assessment alongside your question. The Guardian is set to policy integrity mode — statutory references are checked against current law before deliberation begins.' },
    { n: 2, title: 'The Guardian validates statutory references and sources', body: 'Every statutory reference is checked against current law. Outdated versions, jurisdiction mismatches, and superseded regulations are flagged. Source independence and retraction status are checked for every cited study.' },
    { n: 3, title: 'The Contrarian plays the NAO analyst or committee researcher', body: 'The Contrarian surfaces the objection a NAO analyst, select committee researcher, or judicial review claimant will raise — at maximum temperature, with the strongest possible framing. Unresolved objections appear verbatim with resolution conditions.' },
    { n: 4, title: 'You get a finding and pre-publication action items', body: 'Unresolved objections are translated into concrete pre-publication actions — sensitivity analyses to add, statutory references to update, gaps to address. You publish with a defensible evidence record, not one that generates its first challenge in committee.' },
  ],
  configLabel: 'Policy integrity mode · Guardian configuration',
  configRows: [
    { key: 'Statutory version', val: 'Every statutory reference validated against current law — outdated versions, jurisdiction mismatches, superseded regulations flagged before entering evidence registry' },
    { key: 'Retraction check', val: 'Every cited study cross-referenced against retraction databases — retracted evidence sources flagged Critical' },
    { key: 'Source recency', val: 'Updated publications on cited topics cross-referenced — outdated analysis cited when updated analysis exists flagged' },
    { key: 'Source independence', val: 'Single-source evidence bases and departmental self-citation flagged for independent triangulation' },
    { key: 'NAO benchmarks', val: 'Business case assumptions checked against NAO published benchmarks for programme types — deviations without justification flagged' },
    { key: 'Audit trail', val: 'Full session record exportable — SVS log, objection register, confidence grades, pre-publication action list' },
  ],
  whyTitle: 'What makes it different<br>from departmental review.',
  whyCards: [
    { title: 'Runs the NAO and committee questions in advance', body: 'The Contrarian surfaces the objection a NAO analyst, select committee researcher, or judicial review claimant will raise — at maximum temperature, with the strongest possible framing. The policy team that prepares for these questions before publication controls the outcome.' },
    { title: 'Validates statutory references against current law', body: 'Legal integrity mode checks every statutory reference against current law — outdated versions, jurisdiction mismatches, and superseded regulations are flagged before they enter a ministerial brief or impact assessment. A brief built on a superseded statutory reference becomes a vulnerability in committee.' },
    { title: 'Produces a defensible audit trail', body: 'The full deliberation record is exportable — SVS validation log, objection register, confidence grades, pre-publication action items. For decisions subject to FOI, audit, or judicial review, the deliberation trail demonstrates the rigour of the analysis process.' },
    { title: 'Updates the evidence base, not just the citation', body: 'Legal integrity mode cross-references not just citation accuracy but whether more recent evidence on the same topic exists and was considered. A brief that cites 2021 analysis when 2024 analysis with different findings is available — and available to the committee — is a brief that generates its first challenge in the opening question.' },
    { title: 'No stake in the policy recommendation', body: 'Departmental reviewers want the policy to succeed. Internal analysts want the evidence to hold. Augle has no stake in either. It produces the finding the evidence supports — including the finding that the evidence base doesn\'t support the submission as written.' },
    { title: '$0.60 per Standard session', body: 'A Standard deliberation costs $0.60. A select committee appearance that exposes a methodology weakness costs considerably more in ministerial preparation time and public credibility. The economics of running Augle before publication are straightforward.' },
  ],
  ctaTitle: 'Evidence that holds up<br>to scrutiny — before it\'s public.',
  ctaBody: 'Join the waitlist and get one Standard session free. Run it on a real policy question before your next publication or committee date.',
};

export const FINANCIAL_SERVICES_DATA: VerticalData = {
  slug: 'financial-services', activeSlug: 'financial-services',
  breadcrumbLabel: 'Financial services',
  eyebrow: 'Solutions · Financial services',
  heroTitle: 'Run the regulator\'s<br>review before<br><em class="italic text-terracotta">the meeting.</em>',
  heroBody: 'Financial services operate under a standard of evidence that is adversarial by design. Regulators, auditors, litigation counterparties, and internal risk functions all approach the same analysis with the same objective: finding what didn\'t hold. Augle applies that standard to research quality, compliance positions, and risk model assumptions before the regulator does.',
  personas: [
    'Research analysts stress-testing investment theses and reports',
    'Compliance teams reviewing regulatory position papers',
    'Risk functions validating model assumptions and stress scenarios',
    'Legal teams preparing regulatory submissions and enforcement responses',
  ],
  panelLabel: 'Session configuration · Financial services',
  panelRows: [
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Guardian', value: 'Financial integrity', accent: true },
    { label: 'Depth', value: 'Standard · Deep' },
    { label: 'Documents', value: 'Research reports · compliance papers · model documentation · regulatory submissions' },
    { label: 'SVS checks', value: 'Market data recency · regulatory filing version · forecast vs. historical · financial advice prohibition' },
    { label: 'Output', value: 'Finding · confidence grade · unresolved objections · audit trail' },
  ],
  problemTitle: 'Compliance positions<br>that don\'t survive<br>regulatory scrutiny.',
  problemBody: 'The FCA supervisor, the PRA model validator, and the enforcement team all approach compliance positions, research reports, and risk model assumptions with the same adversarial intent. The question is whether Augle finds the weakness first — or the regulator finds it in the examination meeting.',
  problemQuestions: [
    '"Does our Consumer Duty compliance position hold under the FCA\'s current supervisory approach?"',
    '"Are any of our regulatory citations outdated relative to the FCA\'s current guidance cycle?"',
    '"Does our equity research report present statistical claims that a short-seller will challenge?"',
    '"Do our risk model assumptions hold under the PRA\'s stress test scenarios?"',
  ],
  problemItems: [
    { title: 'Compliance positions that don\'t survive regulatory scrutiny', body: 'Financial integrity mode checks regulatory citations against the current supervisory cycle — outdated Final Rules, superseded guidance, and pre-Brexit regulatory references are flagged. The Contrarian plays the FCA supervisor\'s interpretation challenge before the examination meeting.' },
    { title: 'Research reports with stale or single-source market data', body: 'Financial integrity mode flags market data sourced from a single analyst report, forecasts presented as historical actuals, and market size estimates without triangulation. A research report whose key market assumptions don\'t survive independent scrutiny doesn\'t survive publication.' },
    { title: 'Risk model assumptions untested against tail scenarios', body: 'The Methodologist evaluates whether risk model assumptions hold under the stress scenarios the PRA or internal risk function will apply — and whether the calibration period was representative of the out-of-sample scenarios the model will be tested against.' },
    { title: 'Regulatory citations that are outdated or mis-scoped', body: 'Regulatory environments evolve faster than internal guidance. Legal integrity mode checks every regulatory reference against the current supervisory cycle — outdated Final Rules, post-Brexit regulatory divergences, and superseded guidance are flagged before they enter a compliance position or submission.' },
  ],
  useCasesTitle: 'Two sessions.<br>Two reviews before the meeting.',
  useCasesBody: 'Each scenario is drawn from the Augle Use Case Compendium — hypothetical sessions illustrating deliberation behaviour at critical pre-submission decision points.',
  useCases: [
    {
      num: 'Use case 01 of 02 · Financial services',
      name: 'The Compliance Position Review',
      persona: 'Head of Compliance · Retail investment platform · Pre-FCA supervisory meeting',
      badge: 'Standard depth · document ingestion', badgeVariant: 'standard',
      question: '"Does our Consumer Duty compliance position on the platform\'s default fund selection hold under the FCA\'s current supervisory approach, and what is the strongest regulatory challenge we should be prepared to address?"',
      highlights: [
        { agent: 'Guardian SVS', text: 'Regulatory version check: the compliance position paper cites the 2022 Final Rules. The FCA published a 2024 supervisory letter with materially different expectations on default fund governance that is not reflected in the current position paper.' },
        { agent: 'Cartographer', text: 'Settled: the platform\'s fund selection process meets the 2022 Final Rules requirements. Contested: whether the process meets the FCA\'s 2024 supervisory expectations — the supervisory letter raises specific expectations about annual governance reviews that are not in the current process.' },
        { agent: 'Contrarian', text: 'Strong objection: "The FCA supervisor will arrive with the 2024 supervisory letter. The compliance position paper doesn\'t reference it. Walking into a Consumer Duty examination with a position paper that doesn\'t engage with the supervisor\'s most recent published expectations is the examination risk, not the compliance risk."' },
        { agent: 'Pragmatist', text: 'Two pre-meeting actions: (1) Update position paper to reference and address 2024 supervisory letter expectations. (2) Document the annual governance review process — or implement it before the examination date if it doesn\'t currently exist.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'SVS flag', val: '2024 FCA supervisory letter not referenced — supervisor will have it; position paper doesn\'t address it' },
        { key: 'Finding', val: 'Contested as submitted — 2022 Final Rules compliance demonstrated; 2024 supervisory expectations not addressed' },
        { key: 'Next step', val: 'Update position paper to address 2024 letter, document annual governance review process before examination date' },
      ]},
      value: 'The FCA\'s 2024 supervisory letter was public. The compliance team had the 2022 Final Rules but hadn\'t updated the position paper to reflect the current supervisory cycle. Walking into an examination with a position paper that engages the supervisor\'s stated priorities is a materially different conversation from the one that doesn\'t.',
    },
    {
      num: 'Use case 02 of 02 · Financial services',
      name: 'The Equity Research Review',
      persona: 'Head of Research · Asset management firm · Pre-publication report review',
      badge: 'Standard depth', badgeVariant: 'standard',
      question: '"Does the investment thesis in this initiating coverage report on a mid-cap technology company hold under stress-testing, and what will a short-seller\'s research team find that our team hasn\'t addressed?"',
      highlights: [
        { agent: 'Methodologist', text: 'Statistical claim: the revenue growth CAGR of 34% for years 3-5 is a DCF input, not a historical data point. The report presents it as an evidence-based projection without disclosing the confidence interval or the assumptions driving the outer years.' },
        { agent: 'Contrarian', text: 'Strong objection: "The SMB churn rate assumption is buried in footnote 12 at 8% annually. The comparable SaaS cohort data shows 14-18% churn for this segment. At the comparable churn rate, the year 5 revenue figure drops 22% and the DCF target price drops below the current market price. A short-seller\'s note will make this calculation in the first paragraph."' },
        { agent: 'Pragmatist', text: 'Three additions: (1) Add bear case with comparable churn rate. (2) Add margin analysis adjusted for churn-driven CAC inflation. (3) Disclose the outer-year growth assumptions explicitly rather than embedding them in the DCF. A bull case with a transparent bear case is a more credible research report, not a less bullish one.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'SVS flag', val: 'Three market data points from single sell-side source without independent triangulation' },
        { key: 'Finding', val: 'Probable with transparent assumptions — Contested as currently presented given undisclosed SMB churn sensitivity' },
        { key: 'Key gaps', val: 'SMB churn assumption vs. comparable data; undisclosed outer-year growth assumptions in DCF' },
        { key: 'Next step', val: 'Add bear case with comparable churn, adjust margin analysis, disclose outer-year growth assumptions explicitly' },
      ]},
      value: 'All three gaps were in public sources. A short-seller\'s response note the day after publication would have found all three. A report that addresses them proactively — with a bear case that acknowledges the SMB churn risk — is a more credible piece of research, not a less bullish one.',
    },
  ],
  howTitle: 'Built for the financial<br>services evidence lifecycle.',
  howSteps: [
    { n: 1, title: 'Submit your compliance or research question and upload documents', body: 'Upload the compliance position paper, research report, or model documentation alongside your question. Financial integrity mode activates — regulatory version checks and market data validation run before deliberation begins.' },
    { n: 2, title: 'Financial integrity mode validates regulatory citations and market data', body: 'Every regulatory reference is checked against the current supervisory cycle. Market data is validated for source attribution and recency. Forecasts presented as historical actuals are flagged. The Synthesizer is architecturally forbidden from producing buy/sell/long/short framing.' },
    { n: 3, title: 'The Contrarian plays the regulator\'s challenge', body: 'The Contrarian surfaces the FCA supervisor\'s interpretation challenge, the PRA model validator\'s stress scenario objection, and the short-seller\'s statistical objection — at maximum temperature. Unresolved objections appear verbatim with resolution conditions.' },
    { n: 4, title: 'You get a finding and a pre-meeting action list', body: 'Unresolved objections are translated into concrete pre-meeting actions — regulatory citations to update, sensitivity cases to add, assumptions to disclose. You walk into the examination or publish the report having already addressed the questions that would otherwise define the meeting.' },
  ],
  configLabel: 'Financial integrity mode · Guardian configuration',
  configRows: [
    { key: 'Regulatory version', val: 'Every regulatory reference validated against current supervisory cycle — 2022 Final Rules vs. 2024 supervisory letters, post-Brexit regulatory divergences, superseded guidance flagged' },
    { key: 'Market data', val: 'Market size and growth claims validated for source attribution and recency — single-source or unattributed estimates flagged' },
    { key: 'Forecast vs. actual', val: 'Forward projections presented as historical performance flagged SVS_MISREPRESENTED — evidence node capped at Gap' },
    { key: 'Financial advice', val: 'Synthesizer architecturally forbidden from producing buy/sell/long/short framing in all financial services sessions' },
    { key: 'Model assumptions', val: 'Risk model calibration period evaluated against out-of-sample test scenarios — assumptions untested against tail scenarios flagged' },
    { key: 'Audit trail', val: 'Full session record exportable — SVS regulatory log, objection register with examination preparation items, confidence grades' },
  ],
  whyTitle: 'What makes it different<br>from a compliance review.',
  whyCards: [
    { title: 'Runs the regulator\'s challenge before the meeting', body: 'The Contrarian surfaces the FCA supervisor\'s interpretation challenge, the PRA model validator\'s stress scenario objection, and the enforcement team\'s precedent application — at maximum temperature. The compliance team that prepares for these questions controls the supervisory meeting.' },
    { title: 'Validates market data and regulatory citations automatically', body: 'Financial integrity mode checks every regulatory reference against the current supervisory cycle and every market data point for source attribution and recency. A compliance position built on outdated regulatory guidance doesn\'t survive examination.' },
    { title: 'Produces an auditable record for regulated use', body: 'The full deliberation record — regulatory SVS log, objection register, confidence grades — is exportable. For regulated firms, the audit trail demonstrates the rigour of the compliance review and research quality process.' },
    { title: 'Financial advice framing architecturally prohibited', body: 'The Synthesizer is architecturally forbidden from producing buy/sell/long/short recommendations in financial services sessions. The finding is a calibrated evidence assessment, not investment advice. This prohibition cannot be overridden by any instruction.' },
    { title: 'Bear case surfaced, not suppressed', body: 'The Contrarian is required to surface the strongest version of every challenge to the research thesis — including the SMB churn sensitivity, the regulatory interpretation risk, and the model tail scenario. Unresolved objections appear verbatim. A report that has already addressed these is a more credible report.' },
    { title: '$0.60 per Standard session', body: 'A Standard deliberation costs $0.60. An FCA examination that surfaces a compliance gap costs considerably more to resolve. A short-seller\'s response note the day after publication costs credibility. The economics of running Augle before the meeting are straightforward.' },
  ],
  ctaTitle: 'Run the regulator\'s review<br>before the meeting.',
  ctaBody: 'Join the waitlist and get one Standard session free. Run it on a real compliance or research question before your next regulatory engagement.',
};

export const MEDIA_DATA: VerticalData = {
  slug: 'media', activeSlug: 'media',
  breadcrumbLabel: 'Media + journalism',
  eyebrow: 'Solutions · Media + journalism',
  heroTitle: 'Publish stories<br>that hold.<br><em class="italic text-terracotta">Not ones that retract.</em>',
  heroBody: 'A statistic that doesn\'t survive a statistician\'s Twitter thread. A source whose conflict of interest wasn\'t surfaced. An investigative claim whose primary document has an alternative interpretation the reporter didn\'t consider. These are the corrections that define a publication\'s credibility. Augle runs the adversarial review before publication — so corrections become optional rather than inevitable.',
  personas: [
    'Investigative reporters stress-testing evidence before publication',
    'Editors reviewing statistical claims and source independence',
    'Science journalists translating research findings for public audiences',
    'Data journalism teams validating analysis before publication',
  ],
  panelLabel: 'Session configuration · Media + journalism',
  panelRows: [
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Guardian', value: 'Editorial integrity', accent: true },
    { label: 'Depth', value: 'Standard · Deep' },
    { label: 'Documents', value: 'Draft articles · research papers · data analyses · source documents' },
    { label: 'SVS checks', value: 'Source independence · statistical misrepresentation · primary vs. secondary source · press release vs. peer review' },
    { label: 'Output', value: 'Finding · confidence grade · unresolved objections · audit trail' },
  ],
  problemTitle: 'The correction<br>that defines the<br>publication\'s credibility.',
  problemBody: 'A statistic that misrepresents the underlying study. A press release finding that diverges from what the study actually found. A source with an undisclosed conflict of interest. A legal claim that the subject\'s counsel will challenge before publication. These are the vulnerabilities that generate corrections — or defamation claims. Augle finds them before you publish.',
  problemQuestions: [
    '"Does the statistical claim in our story accurately represent the study, or are we overstating the finding?"',
    '"What is the strongest counter-argument the subject\'s legal team will advance before we publish?"',
    '"Are there sources in this investigation whose independence or conflicts of interest we haven\'t adequately assessed?"',
    '"Does our science story accurately represent what the research found, or are we extrapolating from the press release?"',
  ],
  problemItems: [
    { title: 'Statistics that misrepresent the underlying study', body: 'Editorial integrity mode monitors every statistical claim against the original source — relative risk without absolute baseline, correlation framed as causation, subgroup findings presented as primary results. These are the errors that generate corrections from academic statisticians within 24 hours of publication.' },
    { title: 'Press release findings that diverge from the actual study', body: 'Science journalists frequently translate press release language into stories. The Cartographer goes to the original study — checking whether the press release accurately characterises the methodology, the primary endpoint, the population, and the effect size. When they diverge, the divergence is flagged.' },
    { title: 'Sources with undisclosed conflicts of interest', body: 'The Guardian\'s editorial integrity mode flags source independence concerns — undisclosed funding relationships, institutional affiliations that create incentive misalignment, and expert sources whose public positions diverge from their disclosed financial interests.' },
    { title: 'The strongest counter-argument you haven\'t addressed', body: 'The Contrarian plays the subject\'s legal team, the hostile academic critic, and the rival publication\'s fact-checker — at maximum temperature. Unresolved objections appear verbatim with resolution conditions. A story that has already survived this adversarial review is a story that publishes with confidence.' },
  ],
  useCasesTitle: 'Two sessions.<br>Two stories before publication.',
  useCasesBody: 'Each scenario is drawn from the Augle Use Case Compendium — hypothetical sessions illustrating deliberation behaviour at critical pre-publication decision points.',
  useCases: [
    {
      num: 'Use case 01 of 02 · Media + journalism',
      name: 'The Investigative Pre-Publication Review',
      persona: 'Senior Investigative Reporter · National newspaper · Pre-publication legal and editorial review',
      badge: 'Deep · flagship Contrarian', badgeVariant: 'deep',
      question: '"Does the evidence in this investigation into a major housebuilder\'s planning application practices support the central claim, and what is the strongest counter-argument the subject\'s legal team will advance?"',
      highlights: [
        { agent: 'Cartographer', text: 'Settled: the planning applications were submitted and processed within the documented timeframe. Contested: whether the processing timeline represents preferential treatment or falls within normal variation for applications of this type and local authority. Unknown: whether the comparison set of applications is representative of the appropriate benchmark.' },
        { agent: 'Contrarian', text: 'Strong objection (Unresolved): "The legal team will argue the comparison set is unrepresentative — the article compares large commercial applications to the housebuilder\'s mixed-use applications, which have structurally different processing timelines. This is the pre-publication letter\'s entire argument. The statistical claim needs to hold against the appropriate comparator." Resolution condition: replicate the analysis using mixed-use applications only as the comparison set.' },
        { agent: 'Methodologist', text: 'Construct validity: the comparison methodology — commercial applications as benchmark — does not control for application complexity. The statistical significance of the timeline differential may not hold with an application-type-matched comparator.' },
        { agent: 'Pragmatist', text: 'Commission the mixed-use comparison analysis before publication. If the finding holds — publish with the stronger methodology. If it doesn\'t — the story\'s central statistical claim needs to be reframed to what it can support.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Contested as framed — comparison set validity is the subject\'s strongest legal argument' },
        { key: 'Key gap', val: 'Application-type comparison set mismatch — mixed-use vs. commercial comparator needed' },
        { key: 'Legal risk', val: 'Pre-publication letter will challenge comparator methodology — this is the entire argument' },
        { key: 'Next step', val: 'Replicate analysis with mixed-use comparator — story publishes with stronger or appropriately scoped claim' },
      ]},
      value: 'The alternative explanation was the legal team\'s entire pre-publication letter. The reporter had considered it but the article didn\'t address it directly. A reframed statistical claim with the alternative explanation presented and addressed turned a legally vulnerable story into a defensible one.',
    },
    {
      num: 'Use case 02 of 02 · Media + journalism',
      name: 'The Science Story Review',
      persona: 'Science Editor · Weekly magazine · Pre-publication fact check on a clinical research story',
      badge: 'Standard depth', badgeVariant: 'standard',
      question: '"Does our draft story on a new study linking ultra-processed food consumption to cognitive decline accurately represent what the study actually found, or are we overstating the findings?"',
      highlights: [
        { agent: 'Guardian SVS', text: 'Source check: the story is based on the press release, not the primary study. The press release describes "cognitive decline" as the outcome — the study\'s primary endpoint is "performance on specific cognitive tasks" with a standardised mean difference of 0.18 in the treatment group. The press release language overstates the effect.' },
        { agent: 'Methodologist', text: 'Construct validity: the study measures performance on specific cognitive tasks — not "cognitive decline" as a clinical construct. The study population is healthy adults aged 40-65, not the general population. Causal language is unsupported — this is an observational study with significant confounding.' },
        { agent: 'Contrarian', text: 'Moderate objection: "The study authors will object to the causal framing. The story\'s headline — \'Ultra-processed food causes cognitive decline\' — will generate a correction request from the lead author within 24 hours of publication. The relationship is observational and the effect size is small."' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'SVS flag', val: 'Story based on press release — primary study endpoint differs materially from press release language' },
        { key: 'Finding', val: 'Contested as framed — causal language unsupported; effect size smaller than press release implies' },
        { key: 'Edits needed', val: 'Replace causal language with observational framing; report effect size and population scope accurately; note confounding' },
      ]},
      value: 'The press release was accurate about the relative risk — it just omitted the absolute baseline, the population scope caveat, and the causal language limitation. Four targeted edits turned a story that would have generated a correction from the study\'s authors into one they could endorse.',
    },
  ],
  howTitle: 'Built for the investigative<br>journalism lifecycle.',
  howSteps: [
    { n: 1, title: 'Submit your story question and upload documents', body: 'Upload the draft story, primary research, or source documents alongside your pre-publication question. Editorial integrity mode activates — source independence, statistical claim accuracy, and press release-vs-study divergence are checked before deliberation begins.' },
    { n: 2, title: 'The Guardian checks source independence and statistical accuracy', body: 'Editorial integrity mode monitors every statistical claim against the original source, checks source independence and conflict of interest flags, and validates whether press release language accurately represents the primary study.' },
    { n: 3, title: 'The Contrarian plays the legal team and the hostile critic', body: 'The Contrarian runs at maximum temperature to surface the subject\'s pre-publication legal argument, the hostile academic critic\'s statistical objection, and the rival publication\'s fact-checking challenge. Unresolved objections appear verbatim with resolution conditions.' },
    { n: 4, title: 'You get a finding and pre-publication corrections', body: 'Unresolved objections are translated into targeted pre-publication edits — statistical framings to correct, causal language to qualify, comparator methodologies to rerun. You publish the story that survives the adversarial review, not the one that generates the first correction.' },
  ],
  configLabel: 'Editorial integrity mode · Guardian configuration',
  configRows: [
    { key: 'Statistical claims', val: 'Every statistical claim validated against original source — relative risk without absolute baseline, subgroup findings as primary results, correlation framed as causation — all flagged' },
    { key: 'Press release vs. study', val: 'Press release language compared against primary study endpoints, population, and effect size — divergences flagged' },
    { key: 'Source independence', val: 'Funding relationships, institutional affiliations, and undisclosed conflicts of interest flagged for editorial assessment' },
    { key: 'Primary vs. secondary', val: 'Stories based on secondary sources (press releases, other articles) flagged when primary study is available and diverges' },
    { key: 'Causal language', val: 'Causal framing in observational study coverage flagged — correlation vs. causation distinction enforced' },
    { key: 'Audit trail', val: 'Full session record exportable — SVS log, objection register, pre-publication correction list' },
  ],
  whyTitle: 'What makes it different<br>from editorial fact-checking.',
  whyCards: [
    { title: 'Catches statistical errors before publication', body: 'Editorial integrity mode monitors every statistical claim against the original source — relative risk without absolute baseline, correlation framed as causation, subgroup findings presented as primary results. These are the errors that generate corrections from academic statisticians within 24 hours of publication. Catching them before publication is the entire value.' },
    { title: 'Runs the strongest counter-argument before publication', body: 'The Contrarian plays the subject\'s legal team, the hostile academic critic, and the rival fact-checker — at maximum temperature. A story that has already survived this adversarial review is a story that publishes with confidence. A story that hasn\'t may generate a pre-publication letter that defines the edit.' },
    { title: 'Produces an auditable evidence record', body: 'The full deliberation record — SVS validation log, objection register, pre-publication correction list — is exportable. For investigative journalism, the audit trail demonstrates the rigour of the pre-publication process to editorial leadership and, if necessary, to legal counsel.' },
    { title: 'Primary study vs. press release divergence caught automatically', body: 'Science journalists frequently translate press release language into stories. The Guardian\'s SVS goes to the original study — checking whether the press release accurately characterises the methodology, the primary endpoint, and the effect size. When they diverge, the divergence is flagged before publication.' },
    { title: 'Source independence monitored automatically', body: 'Editorial integrity mode flags source independence concerns — undisclosed funding relationships, institutional affiliations that create incentive misalignment, and expert sources whose public positions diverge from their disclosed financial interests.' },
    { title: '$0.60 per Standard session', body: 'A Standard deliberation costs $0.60. A correction notice that circulates on social media for 48 hours costs credibility that takes months to rebuild. The economics of running Augle before publication are straightforward.' },
  ],
  ctaTitle: 'Publish stories that hold.<br>Not ones that retract.',
  ctaBody: 'Join the waitlist and get one Standard session free. Run it on a real pre-publication question before your next deadline.',
};
