import SolutionLayout, { VerticalData } from '../SolutionLayout';

const data: VerticalData = {
  slug: 'law-firms', activeSlug: 'law-firms',
  breadcrumbLabel: 'Law firms',
  eyebrow: 'Solutions · Law firms',
  heroTitle: 'Run opposing<br>counsel\'s review<br><em class="italic text-terracotta">before they do.</em>',
  heroBody: 'Opposing counsel will stress-test every citation, every expert opinion, and every precedent your case relies on. Augle runs that review first — mapping what\'s settled law, what\'s contested, and where your evidence base is most exposed before you\'re in the room.',
  personas: [
    'Litigation partners preparing expert evidence',
    'Associates conducting case law research',
    'In-house counsel reviewing regulatory applicability',
    'Dispute resolution teams stress-testing arbitration positions',
  ],
  panelLabel: 'Session configuration · Law firms',
  panelRows: [
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Guardian', value: 'Legal integrity', accent: true },
    { label: 'Depth', value: 'Standard · Deep' },
    { label: 'Documents', value: 'Case bundles · Expert reports · Statutes' },
    { label: 'SVS checks', value: 'Case citation · overruled decisions · jurisdiction scope · statutory version' },
    { label: 'Output', value: 'Finding · confidence grade · unresolved objections · audit trail' },
  ],
  problemTitle: 'The cross-examination<br>line you haven\'t<br>prepared for.',
  problemBody: 'Expert reports with methodology opposing counsel will challenge. Case citations that have been overruled or distinguished. Statutory interpretations that don\'t survive current law. The cross-examination question that exposes the weakness in your evidence before you\'ve had a chance to address it.',
  problemQuestions: [
    '"Does our expert\'s methodology meet the Daubert standard given the objections opposing counsel is likely to raise?"',
    '"Are the precedents our submissions rely on still good law in the current appellate landscape?"',
    '"What is the strongest counter-argument to our regulatory applicability position?"',
    '"Which of our expert\'s assumptions will the cross-examination target?"',
  ],
  problemItems: [
    { title: 'Expert reports with methodology opposing counsel will challenge', body: 'The Methodologist evaluates whether your expert\'s approach — comparator selection, loss calculation methodology, sample construction — meets the methodological standard opposing counsel will challenge. Objections that surface here are ones you can brief your expert to address before the hearing, not during it.' },
    { title: 'Case citations that have been overruled or distinguished', body: 'Legal integrity mode checks every case citation against current legal databases — overruled decisions, subsequent distinctions, and jurisdictional inapplicability are flagged before they enter a submission. A precedent that\'s been limited by subsequent appellate decisions doesn\'t survive SVS.' },
    { title: 'Statutory interpretations that don\'t survive current law', body: 'Statutory version mismatches, jurisdiction scope errors, and superseded regulations are invisible in standard desk review — article numbers are similar enough that errors don\'t register. Legal integrity mode checks the current version against your citation.' },
    { title: 'The cross-examination line you haven\'t prepared for', body: 'The Contrarian plays opposing counsel at maximum temperature — finding the strongest version of every challenge to your case theory, your expert\'s methodology, and your precedent line. Unresolved objections appear verbatim with resolution conditions so you can brief your expert specifically.' },
  ],
  useCasesTitle: 'Three sessions.<br>Three moments before the hearing.',
  useCasesBody: 'Each scenario is drawn from the Augle Use Case Compendium — hypothetical sessions illustrating deliberation behaviour at critical pre-hearing decision points.',
  useCases: [
    {
      num: 'Use case 01 of 03 · Law firms',
      name: 'The Expert Evidence Review',
      persona: 'Litigation Partner · Commercial dispute · London arbitration',
      badge: 'Deep · flagship Contrarian', badgeVariant: 'deep',
      question: '"Does our quantum expert\'s loss of profit calculation methodology withstand the methodological objections opposing counsel is likely to raise?"',
      highlights: [
        { agent: 'Cartographer', text: 'Settled: the but-for methodology is accepted in this jurisdiction. Contested: whether the comparator period chosen is appropriate given the sector-wide revenue compression during the period. Unknown: whether opposing counsel has retained an economist specifically on the comparator period issue.' },
        { agent: 'Methodologist', text: 'Construct validity: the comparator period includes months affected by sector-wide supply chain disruption that is not isolated in the analysis. The loss calculation may overstate damages attributable to the breach by failing to account for industry-wide compression.' },
        { agent: 'Contrarian', text: 'Strong objection: "The comparator period is the entire case. Opposing counsel\'s economist will argue that sector-wide compression accounts for 40-60% of the revenue shortfall — and they\'re right that it hasn\'t been isolated. This is the cross-examination line."' },
        { agent: 'Pragmatist', text: 'Commission supplementary analysis isolating sector-wide compression from breach-attributable loss. Brief expert on the specific objection and the prepared response before the Preliminary Meeting.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Contested — comparator period methodology does not adequately isolate sector-wide compression' },
        { key: 'Key objection', val: 'Sector-wide revenue compression not isolated from breach-attributable loss in comparator analysis' },
        { key: 'Next step', val: 'Commission supplementary analysis — expert briefed on objection and prepared response before Preliminary Meeting' },
      ]},
      value: 'The team knew the comparator period was a potential weakness. They didn\'t know opposing counsel had already retained an economist specifically to address the sector-wide revenue compression point. The supplementary analysis was commissioned three weeks before the Preliminary Meeting — not two days before the hearing.',
    },
    {
      num: 'Use case 02 of 03 · Law firms',
      name: 'The Precedent Validity Check',
      persona: 'Senior Associate · Regulatory litigation · Financial services',
      badge: 'Standard depth', badgeVariant: 'standard',
      question: '"Does the line of authority our submissions rely on for the interpretation of \'reasonable steps\' under the Consumer Duty remain good law in the current appellate landscape?"',
      highlights: [
        { agent: 'Guardian SVS', text: 'Case citation check: the primary authority — a 2019 High Court decision — has been considered and distinguished in a 2024 Court of Appeal decision that materially narrows its scope in the regulatory context. The distinction has not been addressed in current submissions.' },
        { agent: 'Cartographer', text: 'Settled: the general principle is established law. Contested: whether the 2024 Court of Appeal distinction applies in the Consumer Duty context — the FCA\'s skeleton argument will make this argument.' },
        { agent: 'Contrarian', text: 'Strong objection: "The 2024 Court of Appeal decision is the FCA\'s first citation in regulatory enforcement. The submissions as drafted invite a distinction that could be avoided with one targeted paragraph addressing the scope of the 2024 reasoning."' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Contested — primary authority distinguished by 2024 Court of Appeal in scope relevant to this matter' },
        { key: 'Next step', val: 'Add one paragraph addressing the 2024 distinction and articulating why the Consumer Duty context falls outside its reasoning' },
        { key: 'SVS flag', val: '2019 High Court decision — distinguished by [2024] EWCA Civ — scope limitation in regulatory context' },
      ]},
      value: 'The 2024 Court of Appeal decision wasn\'t in the junior\'s research file. It would have been in the FCA\'s skeleton argument. Finding it through SVS before filing cost one afternoon of revision. Finding it in the FCA\'s response would have cost considerably more.',
    },
    {
      num: 'Use case 03 of 03 · Law firms',
      name: 'The Data Protection Compliance Review',
      persona: 'In-house Counsel · Global technology company · Pre-implementation review',
      badge: 'Standard depth', badgeVariant: 'standard',
      question: '"Does the proposed data processing architecture comply with the statutory framework under the current version of the UK GDPR and DPA 2018?"',
      highlights: [
        { agent: 'Guardian SVS', text: 'Statutory version check: the internal legal guidance cites Article 6(1)(f) under the 2018 version — the UK GDPR post-Brexit implementation introduced material differences in the legitimate interests basis that are not reflected in the current architecture review.' },
        { agent: 'Methodologist', text: 'Jurisdiction scope: two of the processing activities cross EU/UK jurisdictions in a way that triggers both UK GDPR and EU GDPR compliance requirements. The review addresses UK GDPR only.' },
        { agent: 'Contrarian', text: 'Moderate objection: "The legitimate interests balancing test for the profiling activity is not documented in the architecture. Without a documented DPIA and balancing test, the ICO\'s enforcement risk on this processing activity is material — even if the basis is substantively defensible."' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Contested — statutory version mismatch and jurisdiction scope gap identified; legitimate interests basis not documented' },
        { key: 'Key JR risk 1', val: 'Post-Brexit UK GDPR legitimate interests basis differs materially from EU GDPR — internal guidance not updated' },
        { key: 'Key JR risk 2', val: 'Dual-jurisdiction processing not addressed — EU GDPR compliance review required' },
        { key: 'Next step', val: 'Update internal guidance to post-Brexit UK GDPR, commission EU jurisdiction analysis, and document DPIA for profiling activity' },
      ]},
      value: 'The statutory version mismatch was invisible in internal review. The enforcement risk on the legitimate interests basis was known but not quantified. Augle surfaced both before the architecture was finalised, not after the ICO opened an investigation.',
    },
  ],
  howTitle: 'Built for legal<br>evidence preparation.',
  howSteps: [
    { n: 1, title: 'Submit the case question and upload documents', body: 'Upload the case bundle, expert report, or statutory framework alongside your research question. The Guardian is set to legal integrity mode — case citations are checked against current law before deliberation begins.' },
    { n: 2, title: 'Legal integrity mode validates every citation', body: 'Every case citation is checked against current legal databases. Overruled decisions, subsequent distinctions, statutory version mismatches, and jurisdiction scope errors are flagged before they enter a submission.' },
    { n: 3, title: 'The Contrarian plays opposing counsel', body: 'Running at maximum temperature, the Contrarian surfaces the strongest version of every challenge to your case theory, your expert\'s methodology, and your precedent line. Each objection specifies what would resolve it — which gives you the specific brief for your expert.' },
    { n: 4, title: 'You get a finding and a pre-hearing action list', body: 'Unresolved objections appear verbatim with resolution conditions. The Pragmatist translates these into concrete pre-hearing actions: supplementary analysis to commission, paragraphs to add, experts to brief. You leave with a specific list.' },
  ],
  configLabel: 'Legal integrity mode · Guardian configuration',
  configRows: [
    { key: 'Case citation', val: 'Every case citation checked against current legal databases — overruled decisions, subsequent distinctions, and jurisdictional inapplicability flagged before entering evidence registry' },
    { key: 'Statutory version', val: 'Statutory references validated against current law — post-Brexit UK/EU GDPR divergences, amended articles, and superseded regulations flagged' },
    { key: 'Jurisdiction scope', val: 'Jurisdiction mismatch between cited authority and relevant forum flagged — particularly relevant for cross-border matters' },
    { key: 'Expert methodology', val: 'Methodologist evaluates expert\'s methodological choices — comparator selection, assumption validity, scope of opinion — against the standard the court or tribunal will apply' },
    { key: 'Audit trail', val: 'Full session record exportable — SVS citation log, objection register, confidence grades, and Pragmatist action list' },
  ],
  whyTitle: 'What makes it different<br>from a legal research tool.',
  whyCards: [
    { title: 'Case citations validated automatically', body: 'Legal integrity mode checks every case citation against current legal databases — overruled decisions, subsequent distinctions, and jurisdictional inapplicability are flagged before they enter a submission. A precedent that\'s been limited by subsequent appellate decisions doesn\'t survive SVS. It shouldn\'t survive your review either.' },
    { title: 'The strongest cross-examination surfaced before the hearing', body: "The Contrarian runs at maximum temperature to surface the adversarial framing opposing counsel will deploy. You know the cross-examination line, the objection to your expert's methodology, and the distinction that undermines your precedent — before you're in the room." },
    { title: 'A full audit trail for regulated matters', body: 'The full deliberation record — SVS citation log, objection register, confidence grades — is exportable. For matters before regulators or in circumstances where the quality of legal advice may be scrutinised, the audit trail demonstrates the rigour of the review process.' },
    { title: 'Expert methodology evaluated against the applicable standard', body: "The Methodologist evaluates your expert's methodology against the standard the court, tribunal, or regulator will apply — Daubert, the Ikarian Reefer, or the applicable regulatory test. Objections surface here, not in the hearing." },
    { title: 'Resolution conditions, not vague uncertainty', body: 'Every unresolved objection includes a specific resolution condition — what supplementary analysis, additional authority, or expert instruction would close it. "There is uncertainty" is not an acceptable objection format. You leave knowing exactly what to add.' },
    { title: '$0.60 per Standard session', body: 'A Standard deliberation costs $0.60. A hearing in a significant commercial dispute costs orders of magnitude more per day. The economics of running Augle before those moments are straightforward.' },
  ],
  ctaTitle: 'Run opposing counsel\'s<br>review before they do.',
  ctaBody: 'Join the waitlist and get one Standard session free. Run it on a real case question before your next deadline.',
};

export default function LawFirmsPage() { return <SolutionLayout v={data} />; }
