import { HubData } from './UseCaseHubLayout';

export const RESEARCH_LABS_HUB: HubData = {
  slug: 'research-labs', activeSlug: 'research-labs',
  breadcrumbLabel: 'Research labs',
  eyebrow: 'Use cases · Research labs',
  heroTitle: 'Three sessions.<br>One <em class="italic text-terracotta">vertical.</em>',
  heroBody: "How Augle's ensemble serves corporate and independent research labs — validating experimental findings, stress-testing publication claims, and reviewing competitive landscape assumptions before committing resources.",
  heroLinks: ['Senior scientists reviewing foundational study reproducibility', 'R&D VPs assessing technology readiness levels', 'Strategy directors mapping competitive patent landscapes', 'Principal investigators stress-testing programme assumptions'],
  panelRows: [
    { label: 'Sessions', value: '3 hypothetical' },
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Depths', value: 'Standard · Deep' },
    { label: 'Guardian mode', value: 'Academic / Clinical integrity', accent: true },
    { label: 'Common outputs', value: 'Gap findings · replication risk flags · resolution pathways' },
    { label: 'Solutions page', value: 'Research labs', link: '/solutions/research-labs' },
  ],
  sessions: [
    {
      num: 'Session 01 of 03 · Research labs',
      name: 'The Replication Review',
      persona: 'Senior Scientist, Computational Biology · Genentech',
      question: '"Is the CRISPR off-target editing rate reported in this foundational study reproducible, and what does the replication literature actually show?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Deep', variant: 'deep' }, { label: 'Academic integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Guardian SVS', text: '22 citations verified. One preprint cited as corroborating evidence was never published in peer review. Flagged Moderate. Session continued with preprint downgraded to silver-tier evidence.' },
        { name: 'Synthesizer', text: 'Weight of evidence: Probable that current CRISPR-Cas9 specificity substantially exceeds the foundational claim. Contested that the original figure itself is reproducible using modern assays. Reopen condition: direct replication using matched sequencing depth and contemporary off-target detection methods.' },
        { name: 'Contrarian — Unresolved objection', text: '"Measurement comparability, not replication failure. The canonical off-target rate was measured with superseded sequencing technology. Modern assays would produce a different number. The field has never reconciled this."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested', accent: true },
        { key: 'Confidence', val: '44%' },
        { key: 'Guardian', val: '93% · Academic integrity' },
        { key: 'Key gap', val: 'Sequencing methodology comparability — modern vs. foundational assay' },
      ],
      reopenCondition: 'Independent replication of canonical off-target rate using blind sample preparation and standardised characterisation protocol across at least three independent labs.',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 02 of 03 · Research labs',
      name: 'The Technology Readiness Assessment',
      persona: 'VP Research, Advanced Materials · 3M Corporate R&D',
      question: '"What is the realistic technology readiness level for room-temperature superconducting materials based on the current published evidence, and where is the field actually stuck?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Deep', variant: 'deep' }],
      agentBlocks: [
        { name: 'Synthesizer', text: 'TRL assessment: the field is at TRL 2–3 for pressure-based materials, TRL 1 for ambient-pressure candidates. The Dias retraction is not an isolated failure — it reflects a reproducibility crisis in a field where measurements are extremely sensitive to sample preparation and characterisation protocols. Any corporate investment thesis predicated on near-term room-temperature superconductivity at ambient pressure is not supportable by current evidence.' },
        { name: 'Pragmatist', text: 'Three-part recommendation: (1) Separate the high-pressure TRL trajectory from the ambient-pressure TRL trajectory in any investment framing — they are different bets. (2) Monitor replication literature for 18 months before any materials platform commitment. (3) Focus internal R&D on characterisation methodology, which is the bottleneck regardless of which materials pathway succeeds.' },
        { name: 'Contrarian — Unresolved objection', text: '"Ambient-pressure room-temperature superconductivity claims require independent replication using blind sample preparation and standardised characterisation protocol across at least three independent labs before any commercial TRL assessment is warranted."' },
      ],
      output: [
        { key: 'Finding', val: 'Gap — ambient pressure', accent: true },
        { key: 'Finding', val: 'TRL 2-3 — high pressure' },
        { key: 'Guardian', val: '93% · Academic integrity' },
        { key: 'Key risk', val: 'Reproducibility crisis in characterisation methodology' },
      ],
      reopenCondition: 'Independent replication of any ambient-pressure room-temperature superconductivity claim using blind sample preparation and standardised characterisation protocol across at least three independent labs.',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 03 of 03 · Research labs',
      name: 'The Competitive Intelligence Brief',
      persona: 'Director of Strategy, Pharma R&D · Novartis',
      question: '"What does the published literature actually establish about competitor progress on GLP-1/GIP dual agonists beyond tirzepatide, and where are the unresolved efficacy and safety questions?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Deep', variant: 'deep' }],
      agentBlocks: [
        { name: 'Methodologist', text: 'Competitive landscape limitation: most pipeline data is Phase 2, with heterogeneous endpoints and comparator selection designed to show differentiation rather than head-to-head equivalence. Efficacy comparisons across companies based on Phase 2 data are unreliable. The field lacks a standardised primary endpoint for weight loss trials that would enable valid cross-trial comparisons.' },
        { name: 'Synthesizer', text: 'Confidence grade: Probable for tirzepatide class leadership in current approved agents. Contested for any competitive positioning claim based on pipeline Phase 2 data. Gap for long-term cardiovascular safety of dual vs. triple agonism. Pragmatist recommendation: scope competitive monitoring to include triple agonist candidates as primary threat class.' },
        { name: 'Contrarian — Unresolved objection', text: '"The competitive framing assumes dual agonism is the relevant category. Triple agonist candidates may make this analysis obsolete. The intelligence brief should be re-scoped to include GLP-1/GIP/glucagon compounds as the primary competitive threat."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested on pipeline claims', accent: true },
        { key: 'Guardian', val: '91% · Academic integrity' },
        { key: 'Key gap', val: 'No standardised endpoint for cross-trial comparison' },
        { key: 'Reframe', val: 'Triple agonists are the primary competitive threat class' },
      ],
      unresolvedObjection: '"The competitive framing assumes dual agonism is the relevant category. Triple agonist candidates may make this analysis obsolete. The intelligence brief should be re-scoped to include GLP-1/GIP/glucagon compounds as the primary competitive threat."',
      sessionLink: '/outcomes',
    },
  ],
  relatedCards: [
    { eyebrow: 'Solutions page', name: 'Research labs', desc: 'The full solutions page for this vertical — problem framing, configuration panel, and why Augle for research labs.', href: '/solutions/research-labs' },
    { eyebrow: 'Related hub', name: 'Universities + academia hub', desc: 'Three sessions for PhD candidates, faculty researchers, and academic grant applicants.', href: '/use-cases/universities' },
    { eyebrow: 'Related hub', name: 'Healthcare + life sciences hub', desc: 'Clinical evidence review, HTA submission, and trial design sessions — adjacent patterns for pharma and biotech.', href: '/use-cases/healthcare' },
  ],
  ctaTitle: 'Run a real session<br>on your question.',
  ctaBody: 'Join the waitlist and get one Standard session free — real deliberation, not a simulation.',
  ctaSolutionHref: '/solutions/research-labs',
  ctaSolutionLabel: 'Research labs solutions page',
};

export const POLICY_HUB: HubData = {
  slug: 'policy', activeSlug: 'policy',
  breadcrumbLabel: 'Policy + lawmakers',
  eyebrow: 'Use cases · Policy + lawmakers',
  heroTitle: 'Three sessions.<br>One <em class="italic text-terracotta">vertical.</em>',
  heroBody: 'How the ensemble serves legislative staff, policy advisors, and regulatory analysts — reviewing the evidence base behind proposed legislation and stress-testing counterarguments before committee hearings.',
  heroLinks: ['Senior policy analysts preparing legislative evidence reviews', 'CBO analysts stress-testing bill scoring assumptions', 'State commissioners reviewing public health mandate evidence', 'Congressional staff preparing for committee hearings'],
  panelRows: [
    { label: 'Sessions', value: '3 hypothetical' },
    { label: 'Mode', value: 'Letters & Science · Prediction Markets' },
    { label: 'Depths', value: 'Standard · Deep' },
    { label: 'Guardian mode', value: 'Editorial / Policy integrity', accent: true },
    { label: 'Common outputs', value: 'Contested findings · dissent flags · evidence gap register' },
    { label: 'Solutions page', value: 'Policy', link: '/solutions/policy' },
  ],
  sessions: [
    {
      num: 'Session 01 of 03 · Policy + lawmakers',
      name: 'The Regulatory Impact Review',
      persona: 'Senior Policy Analyst, Senate Commerce Committee',
      question: '"What does the evidence base actually establish about the economic impact of algorithmic content moderation on small publishers, and where are the critical evidentiary gaps?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Editorial integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Guardian SVS', text: '31 citations verified. One industry-funded study cited as independent evidence was produced by a trade association whose members have direct financial interest in the regulatory outcome. Flagged Moderate — disclosed to deliberation. Evidence downgraded but retained.' },
        { name: 'Synthesizer', text: 'Confidence: Probable that algorithmic changes have reduced traffic to independent publishers. Contested whether this constitutes actionable economic harm distinguishable from market competition. Gap on causal mechanism. Legislative recommendation: commission disaggregated study before drafting enforcement mechanisms.' },
        { name: 'Contrarian — Unresolved objection', text: '"The evidence conflates three legally distinct phenomena. Legislation drafted on this composite evidentiary base will not correspond to any single enforceable regulatory category. Disaggregated evidence is required before mechanism design."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — causal mechanism unresolved', accent: true },
        { key: 'Guardian', val: '92% · Editorial integrity' },
        { key: 'SVS flag', val: 'Trade association study — financial interest disclosed' },
        { key: 'Gap', val: 'Disaggregated evidence by legal category required before mechanism design' },
      ],
      unresolvedObjection: '"The evidence conflates three legally distinct phenomena. Legislation drafted on this composite evidentiary base will not correspond to any single enforceable regulatory category. Disaggregated evidence is required before mechanism design."',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 02 of 03 · Policy + lawmakers',
      name: 'The Infrastructure Bill Scoring',
      persona: 'Deputy Director, Congressional Budget Office',
      question: '"What does the infrastructure investment literature establish about the employment multiplier effects of broadband expansion, and how reliable are the projections used in the current bill scoring?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Deep', variant: 'deep' }],
      agentBlocks: [
        { name: 'Methodologist', text: 'Scoring methodology concern: the current bill scoring uses a 1.7 multiplier derived from a 2019 meta-analysis that pooled studies with heterogeneous regional contexts. Applying a pooled multiplier to a geographically targeted programme introduces systematic bias. Rural-specific multiplier estimates cluster lower (0.8–1.2). The gap between used multiplier and rural-specific estimates implies the employment projection may be overstated by 30–40%.' },
        { name: 'Pragmatist', text: 'Two-track recommendation: (1) Report scoring range rather than point estimate — present 0.8 to 1.7 multiplier band with explicit assumptions. (2) Flag the macroeconomic context dependency explicitly in the bill report language to prevent the scoring from being cited as precision it does not support.' },
        { name: 'Contrarian — Unresolved objection', text: '"Rural-specific multiplier meta-analysis using post-2020 data with remote work employment included as an outcome category, enabling updated scoring that reflects current baseline broadband penetration, does not yet exist. The current evidence base cannot support a point estimate."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — point estimate not supported', accent: true },
        { key: 'Guardian', val: '95% · Editorial integrity' },
        { key: 'Key gap', val: 'Rural-specific post-2020 multiplier data unavailable' },
        { key: 'Recommendation', val: 'Report as range (0.8–1.7) not point estimate' },
      ],
      reopenCondition: 'Rural-specific multiplier meta-analysis using post-2020 data with remote work employment included as an outcome category.',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 03 of 03 · Policy + lawmakers',
      name: 'The Public Health Mandate Review',
      persona: 'State Health Commissioner, Governor\'s Office',
      question: '"What does the evidence base establish about the effectiveness of indoor masking mandates in reducing COVID-19 transmission in community settings, and what do the most rigorous studies show?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Deep', variant: 'deep' }],
      agentBlocks: [
        { name: 'Guardian SVS', text: '44 citations verified. One Cochrane review frequently cited as definitive evidence against community masking was updated in 2023 with revised conclusions. The original 2020 version is still being cited. Flagged Critical — session used updated 2023 version only.' },
        { name: 'Contrarian — Unresolved objection', text: '"The literature on respirators vs. surgical masks vs. cloth masks is being treated as a single evidence base. These are different interventions with different mechanisms and different evidence profiles. Policy recommendations that specify \'masking\' without specifying mask type are not grounded in what the evidence actually shows."' },
        { name: 'Synthesizer', text: 'The evidence base treats N95 respirators, surgical masks, and cloth masks as equivalent interventions. They are not. Policy that specifies masking without specifying type cannot be grounded in what the literature actually shows.' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — mask-type distinction critical', accent: true },
        { key: 'Guardian', val: '94% · Editorial integrity' },
        { key: 'SVS flag', val: 'Critical — outdated Cochrane version still cited in public record' },
        { key: 'Key gap', val: 'No aggregate evidence base can be cited without mask-type stratification' },
      ],
      unresolvedObjection: '"The evidence base treats N95 respirators, surgical masks, and cloth masks as equivalent interventions. They are not. Policy that specifies masking without specifying type cannot be grounded in what the literature actually shows."',
      sessionLink: '/outcomes',
    },
  ],
  relatedCards: [
    { eyebrow: 'Solutions page', name: 'Policy + lawmakers', desc: 'The full solutions page for this vertical — problem framing, configuration panel, and why Augle for policy work.', href: '/solutions/policy' },
    { eyebrow: 'Related hub', name: 'Government hub', desc: 'Business case reviews, ministerial briefs, and judicial review risk assessments — adjacent patterns for public sector teams.', href: '/use-cases/government' },
    { eyebrow: 'Related hub', name: 'Think tanks hub', desc: 'Pre-publication reviews, advocacy position stress-testing, and grant evaluation — adjacent patterns for policy research organisations.', href: '/use-cases/think-tanks' },
  ],
  ctaTitle: 'Run a real session<br>on your question.',
  ctaBody: 'Join the waitlist and get one Standard session free — real deliberation, not a simulation.',
  ctaSolutionHref: '/solutions/policy',
  ctaSolutionLabel: 'Policy solutions page',
};

export const LAW_FIRMS_HUB: HubData = {
  slug: 'law-firms', activeSlug: 'law-firms',
  breadcrumbLabel: 'Law firms',
  eyebrow: 'Use cases · Law firms',
  heroTitle: 'Three sessions.<br>One <em class="italic text-terracotta">vertical.</em>',
  heroBody: "How the ensemble serves litigation partners, senior associates, and in-house counsel — reviewing expert evidence, verifying case citations, and running opposing counsel's cross-examination before the hearing.",
  heroLinks: ['Litigation partners stress-testing expert witness methodology', 'Senior associates verifying case citation currency', 'Regulatory counsel reviewing compliance position exposure', 'In-house general counsel assessing enforcement risk profiles'],
  panelRows: [
    { label: 'Sessions', value: '3 hypothetical' },
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Depths', value: 'Standard · Deep' },
    { label: 'Guardian mode', value: 'Legal integrity', accent: true },
    { label: 'Common outputs', value: 'Contested findings · cross-examination objections · citation validity flags' },
    { label: 'Solutions page', value: 'Law firms', link: '/solutions/law-firms' },
  ],
  sessions: [
    {
      num: 'Session 01 of 03 · Law firms',
      name: 'The Expert Witness Preparation',
      persona: 'Litigation Partner, Antitrust · Cleary Gottlieb',
      question: '"Does the economic literature support the claim that the merger resulted in consumer harm through coordinated effects, and what will the opposing expert challenge?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Deep', variant: 'deep' }, { label: 'Legal integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Methodologist', text: "Econometric concern: the plaintiff's expert uses a pricing correlation analysis that does not control for common cost shocks. In markets with shared input costs (relevant here: energy), price correlation is expected even absent coordination. This is a standard critique that defence experts routinely make and courts have accepted as sufficient to exclude correlation-based testimony under Daubert." },
        { name: 'Synthesizer', text: 'Confidence: Probable that coordinated effects theory is applicable to the market structure. Contested whether current econometric evidence survives Daubert challenge. Gap on the withheld communications question, which is outside the evidentiary record available for deliberation.' },
        { name: 'Contrarian — Unresolved objection', text: '"The withheld communications question is outside the deliberation record. If the privilege log indicates pre-announcement competitor communications were withheld, the litigation theory may need to shift from coordinated effects to direct evidence. This requires discovery motion, not expert testimony."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested on Daubert survivability', accent: true },
        { key: 'Confidence', val: '47%' },
        { key: 'Guardian', val: '97% · Legal integrity' },
        { key: 'Key risk', val: 'Cost shock control omission — standard Daubert ground' },
      ],
      unresolvedObjection: '"The withheld communications question is outside the deliberation record. If the privilege log indicates pre-announcement competitor communications were withheld, the litigation theory may need to shift from coordinated effects to direct evidence."',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 02 of 03 · Law firms',
      name: 'The Contract Damages Quantification',
      persona: 'Senior Associate, Commercial Litigation · Quinn Emanuel',
      question: '"What methodologies for lost profits quantification in software licence breach cases are most likely to survive Daubert scrutiny, and where is our damages expert most vulnerable?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Legal integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Methodologist', text: "Vulnerability analysis: the before-and-after method used by current expert requires a clean pre-breach baseline. The defendant will argue the pre-breach period included an anomalous customer acquisition campaign that inflates the baseline. This argument succeeded in Oracle v. SAP and the Ninth Circuit affirmed exclusion of expert testimony that did not address the baseline anomaly." },
        { name: 'Pragmatist', text: "Two pre-trial actions: (1) Commission a supplemental expert declaration that explicitly distinguishes the Oracle/SAP baseline problem and explains why the acquisition campaign does not create the same anomaly. (2) Prepare a Daubert opposition brief that front-runs the baseline challenge rather than responding to it." },
        { name: 'Contrarian — Unresolved objection', text: '"Defendant moves to exclude on Oracle/SAP baseline grounds. Supplemental declaration distinguishing the factual record should be prepared before motion practice."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — baseline anomaly unaddressed', accent: true },
        { key: 'Guardian', val: '94% · Legal integrity' },
        { key: 'Key risk', val: 'Oracle/SAP baseline challenge — Ninth Circuit precedent' },
        { key: 'Action', val: 'Supplemental declaration distinguishing factual record before motion practice' },
      ],
      unresolvedObjection: '"Defendant moves to exclude on Oracle/SAP baseline grounds. Supplemental declaration distinguishing the factual record should be prepared before motion practice."',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 03 of 03 · Law firms',
      name: 'The Regulatory Enforcement Preview',
      persona: 'Regulatory Counsel, Financial Services · Sullivan & Cromwell',
      question: '"Based on SEC enforcement patterns over the last five years, what is the realistic exposure profile for our client on the material non-public information question, and how is the current examiner likely to characterise the conduct?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Deep', variant: 'deep' }],
      agentBlocks: [
        { name: 'Cartographer', text: "Pattern analysis: in 18 of 23 recent actions, the SEC's primary evidence was trading timing relative to material announcement, not direct evidence of information receipt. The temporal correlation standard has been applied increasingly aggressively since 2022. Your client's trading window falls within the pattern the enforcement staff uses to establish the rebuttable presumption." },
        { name: 'Synthesizer', text: "Prediction Markets confidence: Probable (61%) that the exam results in a Wells Notice if the trading window analysis is the primary evidence. Contested whether it results in a formal enforcement action without documented insider contact. Recommended posture: prepare a Wells submission that leads with the no-contact argument and addresses the timing correlation affirmatively." },
        { name: 'Contrarian — Unresolved objection', text: '"The timing correlation standard has been applied aggressively since 2022, but 14 of 18 recent timing-based actions had documented insider contact. Without direct contact evidence, enforcement action probability drops materially. The Wells submission should lead with this distinction."' },
      ],
      output: [
        { key: 'Finding', val: 'Probable — Wells Notice (61%)', accent: true },
        { key: 'Guardian', val: '97% · Legal integrity' },
        { key: 'Key distinction', val: 'No documented insider contact — materially reduces enforcement probability' },
        { key: 'Wells posture', val: 'Lead with no-contact argument; address timing correlation affirmatively' },
      ],
      unresolvedObjection: '"The timing correlation standard has been applied aggressively since 2022, but 14 of 18 recent timing-based actions had documented insider contact. Without direct contact evidence, enforcement action probability drops materially."',
      sessionLink: '/outcomes',
    },
  ],
  relatedCards: [
    { eyebrow: 'Solutions page', name: 'Law firms', desc: 'The full solutions page for this vertical — problem framing, configuration panel, and why Augle for legal practice.', href: '/solutions/law-firms' },
    { eyebrow: 'Related hub', name: 'Financial services hub', desc: 'Compliance position reviews, equity research stress-testing, and regulatory enforcement pattern analysis.', href: '/use-cases/financial-services' },
    { eyebrow: 'Related hub', name: 'Government hub', desc: 'Judicial review risk assessments and regulatory impact analysis — adjacent patterns for public law matters.', href: '/use-cases/government' },
  ],
  ctaTitle: 'Run a real session<br>on your question.',
  ctaBody: 'Join the waitlist and get one Standard session free — real deliberation, not a simulation.',
  ctaSolutionHref: '/solutions/law-firms',
  ctaSolutionLabel: 'Law firms solutions page',
};

export const VC_HUB: HubData = {
  slug: 'venture-capital', activeSlug: 'venture-capital',
  breadcrumbLabel: 'Venture capital + PE',
  eyebrow: 'Use cases · Venture capital + PE',
  heroTitle: 'Three sessions.<br>One <em class="italic text-terracotta">vertical.</em>',
  heroBody: 'How the ensemble serves VC partners, PE associates, and growth equity teams — stress-testing investment theses, TAM assumptions, and acquisition diligence before investment committee.',
  heroLinks: ['Deep tech partners reviewing foundational technical claims', 'Growth equity principals validating market sizing assumptions', 'PE managing directors assessing LBO covenant risk', 'Portfolio company boards evaluating strategic initiatives'],
  panelRows: [
    { label: 'Sessions', value: '3 hypothetical' },
    { label: 'Mode', value: 'Letters & Science · Prediction Markets' },
    { label: 'Depths', value: 'Standard · Deep' },
    { label: 'Guardian mode', value: 'Financial / Academic integrity', accent: true },
    { label: 'Common outputs', value: 'Contested TAM claims · diligence gaps · IC preparation items' },
    { label: 'Solutions page', value: 'Venture capital + PE', link: '/solutions/venture-capital' },
  ],
  sessions: [
    {
      num: 'Session 01 of 03 · Venture capital + PE',
      name: 'The Technical Due Diligence',
      persona: 'Partner, Deep Tech · Sequoia Capital',
      question: '"Does the evidence support the founding team\'s claims about their photonic computing chip achieving commercially relevant inference throughput at competitive power efficiency?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Deep', variant: 'deep' }, { label: 'Academic integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Methodologist', text: "Claims analysis: the company's benchmark figures use INT8 precision. Competitive AI accelerators (NVIDIA H100, AMD MI300X) are benchmarked at FP16/BF16. Comparing INT8 photonic throughput to FP16 GPU throughput produces an inflated efficiency ratio. The honest comparison requires matched-precision benchmarking that has not been published. This changes the headline efficiency claim by approximately 4×." },
        { name: 'Synthesizer', text: 'Confidence: Contested that commercial claims are supported by published evidence. Gap on memory-bandwidth-constrained production performance. Diligence recommendation: require matched-precision third-party benchmarking in a production-representative environment before term sheet.' },
        { name: 'Contrarian — Unresolved objection', text: '"Photonic advantage disappears in memory-bandwidth-constrained environments. No study has characterised production inference throughput under real host memory constraints. The demo environment was a single-tenant rack — not representative of production deployment."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — benchmark methodology mismatch', accent: true },
        { key: 'Guardian', val: '93% · Academic integrity' },
        { key: 'Key gap', val: 'Memory-bandwidth-constrained production performance unmeasured' },
        { key: 'Diligence action', val: 'Require matched-precision third-party benchmarking before term sheet' },
      ],
      unresolvedObjection: '"Photonic advantage disappears in memory-bandwidth-constrained environments. No study has characterised production inference throughput under real host memory constraints."',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 02 of 03 · Venture capital + PE',
      name: 'The Market Sizing Validation',
      persona: 'Principal, Growth Equity · General Atlantic',
      question: '"Is the TAM claim of $47B for AI-enabled clinical documentation software by 2029 defensible, and what are the key assumptions that would have to fail for the projection to be wrong?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }],
      agentBlocks: [
        { name: 'Methodologist', text: "Projection methodology: the company's TAM was built bottom-up from per-physician pricing × physician count × penetration rate. The penetration rate assumption (68% by 2029) has no historical analogue in healthcare software. The fastest healthcare software category adoption on record is electronic prescribing, which reached 68% penetration in 11 years from regulatory mandate. AI documentation has no regulatory mandate." },
        { name: 'Pragmatist', text: 'Diligence focus: the price point assumption is more fragile than the penetration assumption. Model sensitivity: at $60/physician/month (current add-on comp), TAM is $16B at 68% penetration — still a large market but changes the return model. Request bottoms-up pricing analysis with customer willingness-to-pay data before closing.' },
        { name: 'Contrarian — Unresolved objection', text: '"Customer willingness-to-pay survey with ≥200 physician respondents across at least three health system types, with pricing elasticity analysis at $60, $120, and $180/month price points, does not exist in the current data room."' },
      ],
      output: [
        { key: 'Finding', val: 'Probable at $16B — Gap at $47B', accent: true },
        { key: 'Guardian', val: '90% · Financial integrity' },
        { key: 'Key fragility', val: 'Penetration rate has no healthcare software analogue without regulatory mandate' },
        { key: 'Diligence action', val: 'Willingness-to-pay survey at three price points before closing' },
      ],
      reopenCondition: 'Customer willingness-to-pay survey with ≥200 physician respondents across at least three health system types, with pricing elasticity analysis at $60, $120, and $180/month price points.',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 03 of 03 · Venture capital + PE',
      name: 'The Portfolio Company Stress Test',
      persona: 'Managing Director, PE · Apollo Global Management',
      question: '"Given rising interest rates and the current covenant structure, what does the evidence on leveraged buyout refinancing outcomes suggest about our probability of covenant breach in the next 18 months?"',
      tags: [{ label: 'Prediction Markets', variant: 'markets' }, { label: 'Deep', variant: 'deep' }],
      agentBlocks: [
        { name: 'Cartographer', text: 'Historical base rates: in the 2008–2009 cycle, LBO covenant breach rates for deals with coverage ratios below 1.5× reached 34% within 18 months of the rate shock onset. Current portfolio company has 1.6× coverage. Base rate breach probability at this coverage level in comparable cycles: approximately 22%. If EBITDA deteriorates 10% (within forecast range), coverage drops to 1.44× and breach probability rises to 31%.' },
        { name: 'Synthesizer', text: 'Prediction Markets confidence: 22–31% breach probability range under base and downside EBITDA scenarios using 2008 comps; 14–20% using 2015 energy comps. Recommend: run both scenarios in board materials and present as a range rather than a point estimate. Active refinancing pursuit is warranted regardless of which base rate is correct.' },
        { name: 'Contrarian — Unresolved objection', text: '"The choice of 2008 vs. 2015 comparison class drives a 2× difference in breach probability. The 2015 energy sector comps may be more appropriate given open credit markets, but this assumption should be validated with the credit team before board presentation."' },
      ],
      output: [
        { key: 'Finding', val: 'Probable — 22–31% breach risk', accent: true },
        { key: 'Guardian', val: '95% · Financial integrity' },
        { key: 'Key uncertainty', val: '2008 vs. 2015 comparison class — 2× difference in outcome' },
        { key: 'Action', val: 'Present as probability range, pursue refinancing regardless' },
      ],
      unresolvedObjection: '"The choice of 2008 vs. 2015 comparison class drives a 2× difference in breach probability. This assumption should be validated with the credit team before board presentation."',
      sessionLink: '/outcomes',
    },
  ],
  relatedCards: [
    { eyebrow: 'Solutions page', name: 'Venture capital + PE', desc: 'The full solutions page for this vertical — problem framing, configuration panel, and why Augle for investment decisions.', href: '/solutions/venture-capital' },
    { eyebrow: 'Related hub', name: 'Enterprise hub', desc: 'Market entry reviews, M&A integration risk, and operational excellence benchmarking — adjacent patterns for corporate development.', href: '/use-cases/enterprise' },
    { eyebrow: 'Related hub', name: 'Financial services hub', desc: 'Credit risk model validation, rates strategy review, and compliance risk briefs.', href: '/use-cases/financial-services' },
  ],
  ctaTitle: 'Run a real session<br>on your question.',
  ctaBody: 'Join the waitlist and get one Standard session free — real deliberation, not a simulation.',
  ctaSolutionHref: '/solutions/venture-capital',
  ctaSolutionLabel: 'VC + PE solutions page',
};

export const THINK_TANKS_HUB: HubData = {
  slug: 'think-tanks', activeSlug: 'think-tanks',
  breadcrumbLabel: 'Think tanks',
  eyebrow: 'Use cases · Think tanks + nonprofits',
  heroTitle: 'Three sessions.<br>One <em class="italic text-terracotta">vertical.</em>',
  heroBody: 'How the ensemble serves research directors, advocacy teams, and programme officers — running adversarial pre-publication review on policy papers, campaign evidence bases, and grant-funded research claims.',
  heroLinks: ['Senior fellows stress-testing pre-publication working papers', 'Policy directors reviewing advocacy evidence for hostile scrutiny', 'Programme officers evaluating grant-funded research methodology', 'Communications teams preparing for hostile media questions'],
  panelRows: [
    { label: 'Sessions', value: '3 hypothetical' },
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Depths', value: 'Standard · Deep' },
    { label: 'Guardian mode', value: 'Academic / Editorial integrity', accent: true },
    { label: 'Common outputs', value: 'Pre-publication edits · evidence scope corrections · grant conditions' },
    { label: 'Solutions page', value: 'Think tanks', link: '/solutions/think-tanks' },
  ],
  sessions: [
    {
      num: 'Session 01 of 03 · Think tanks + nonprofits',
      name: 'The Pre-Publication Evidence Review',
      persona: 'Senior Fellow, Economic Policy · Brookings Institution',
      question: '"Does the evidence base support our working paper\'s claim that universal basic income pilots produce sustained labour market participation effects, and what will peer reviewers challenge?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Academic integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Guardian SVS', text: "19 citations verified. One frequently cited Stockton pilot analysis is a preliminary report by the programme's own evaluation team, not an independent peer-reviewed study. Flagged Moderate — retained but disclosed as non-independent." },
        { name: 'Contrarian — Unresolved objection', text: '"The paper pools pilots across dramatically different income contexts: Stockton (California median income), Finland (Nordic welfare state), and Kenya (subsistence economy). Treating these as a unified evidentiary base for a claim about labour market participation conflates three different underlying phenomena. A peer reviewer in development economics will reject this on external validity grounds."' },
        { name: 'Synthesizer', text: 'Confidence: 39%. The cross-context pooling produces an external validity problem that the paper does not address. The finding is defensible for high-income contexts separately. Reframing recommendation: restrict claim to high-income contexts or run separate analyses by income context.' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — cross-context pooling invalid', accent: true },
        { key: 'Confidence', val: '39%' },
        { key: 'Guardian', val: 'Academic integrity' },
        { key: 'Edit needed', val: 'Restrict claim to high-income contexts or run separate analyses by income context' },
      ],
      unresolvedObjection: '"Pooling pilots across income contexts as a unified evidence base conflates three different phenomena. A development economics reviewer will reject the external validity of cross-context pooling."',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 02 of 03 · Think tanks + nonprofits',
      name: 'The Advocacy Position Stress Test',
      persona: 'Policy Director, Climate Advocacy · Environmental Defense Fund',
      question: '"Is our advocacy position that a $50/tonne carbon price is sufficient to achieve the 2030 emissions reduction targets defensible against the best counter-arguments?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Editorial integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Methodologist', text: "Model dependency: the $50/tonne sufficiency claim is derived from a specific IAM (Integrated Assessment Model) with energy sector assumptions that are contested in the literature. Alternative models using higher baseline fossil fuel demand produce required prices of $80–120/tonne for the same target. The claim is sensitive to model selection in a way the advocacy document does not disclose." },
        { name: 'Pragmatist', text: 'Reframing recommendation: shift advocacy from a specific price point ($50/tonne) to a price pathway (starting at $30, escalating $15/year) with a defined sufficiency test (annual emissions inventory). This is technically stronger, harder to refute on model-dependency grounds, and reflects how effective carbon pricing has actually worked in practice.' },
        { name: 'Contrarian', text: '"Advocacy position updated to advocate for price pathway with automatic adjustment rather than specific price level, removing the model-dependency vulnerability." — objection resolved by reframe.' },
      ],
      output: [
        { key: 'Finding', val: 'Probable — after reframe', accent: true },
        { key: 'Guardian', val: '89% · Editorial integrity' },
        { key: 'Key vulnerability', val: 'IAM model-dependency not disclosed — contested by alternative models' },
        { key: 'Reframe', val: 'Price pathway with automatic adjustment vs. point estimate' },
      ],
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 03 of 03 · Think tanks + nonprofits',
      name: 'The Grant Evaluation Panel',
      persona: 'Program Officer, Science & Technology · MacArthur Foundation',
      question: '"Among these three proposals for AI safety research, which represents the strongest evidence base for impact, and what are the most significant methodological weaknesses in each?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Deep', variant: 'deep' }, { label: 'Academic integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Synthesizer', text: 'Comparative assessment: Proposal A (interpretability) has the strongest near-term empirical tractability but the weakest connection to safety outcomes. Proposal B (robustness) has clear safety relevance but evaluation methodology relies on benchmark saturation that may not transfer to real adversarial conditions. Proposal C (alignment formalisation) is the most theoretically ambitious and the least falsifiable — success criteria are not operationalised.' },
        { name: 'Pragmatist', text: 'Recommendation hierarchy depends on evaluation criterion: Near-term empirical tractability → Proposal A. Safety relevance by mechanism → Proposal B. Potential for field-defining impact → Proposal C. The foundation should make the criterion explicit before ranking. All three have material methodological weaknesses that should be addressed in grant conditions.' },
        { name: 'Contrarian — Unresolved objection', text: '"Evaluating by methodological quality vs. by expected catastrophic risk reduction produces a different proposal ranking. The foundation must make its evaluation criterion explicit before the panel can produce a defensible recommendation."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — criterion-dependent ranking', accent: true },
        { key: 'Guardian', val: '94% · Academic integrity' },
        { key: 'Key gap', val: 'Evaluation criterion must be made explicit before panel ranking' },
        { key: 'Recommendation', val: 'Conditional grants with methodology condition for all three' },
      ],
      unresolvedObjection: '"Evaluating by methodological quality vs. by expected catastrophic risk reduction produces a different proposal ranking. The foundation must make its evaluation criterion explicit before the panel can produce a defensible recommendation."',
      sessionLink: '/outcomes',
    },
  ],
  relatedCards: [
    { eyebrow: 'Solutions page', name: 'Think tanks + nonprofits', desc: 'The full solutions page for this vertical — problem framing, configuration panel, and why Augle for policy research.', href: '/solutions/think-tanks' },
    { eyebrow: 'Related hub', name: 'Universities + academia hub', desc: 'Dissertation defence, systematic review gaps, and grant proposal reviews — adjacent patterns for academic research.', href: '/use-cases/universities' },
    { eyebrow: 'Related hub', name: 'Policy + lawmakers hub', desc: 'Legislative evidence reviews, bill scoring, and public health mandate analysis.', href: '/use-cases/policy' },
  ],
  ctaTitle: 'Run a real session<br>on your question.',
  ctaBody: 'Join the waitlist and get one Standard session free — real deliberation, not a simulation.',
  ctaSolutionHref: '/solutions/think-tanks',
  ctaSolutionLabel: 'Think tanks solutions page',
};

export const ENTERPRISE_HUB: HubData = {
  slug: 'enterprise', activeSlug: 'enterprise',
  breadcrumbLabel: 'Enterprise',
  eyebrow: 'Use cases · Enterprise',
  heroTitle: 'Three sessions.<br>One <em class="italic text-terracotta">vertical.</em>',
  heroBody: 'How the ensemble serves strategy teams, corporate development, and procurement functions — stress-testing market entry analyses, vendor claims, and competitive intelligence before board-level decisions.',
  heroLinks: ['CSOs reviewing strategic initiative evidence bases', 'Corporate development VPs assessing M&A synergy assumptions', 'COOs evaluating operational excellence vendor claims', 'Procurement heads validating ROI and capability claims'],
  panelRows: [
    { label: 'Sessions', value: '3 hypothetical' },
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Depths', value: 'Standard · Deep' },
    { label: 'Guardian mode', value: 'Enterprise / Financial integrity', accent: true },
    { label: 'Common outputs', value: 'Board preparation items · assumption gap flags · vendor claim corrections' },
    { label: 'Solutions page', value: 'Enterprise', link: '/solutions/enterprise' },
  ],
  sessions: [
    {
      num: 'Session 01 of 03 · Enterprise',
      name: 'The Strategic Initiative Review',
      persona: 'Chief Strategy Officer · Fortune 100 Consumer Goods',
      question: '"Does the evidence support our hypothesis that direct-to-consumer channel expansion will improve gross margin by 8–12 points over three years, and what are the assumptions most likely to fail?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Deep', variant: 'deep' }],
      agentBlocks: [
        { name: 'Methodologist', text: "Calculation methodology concern: the 8–12 point margin improvement figure assumes customer acquisition costs (CAC) are classified as marketing expense, not COGS. If CAC is treated as a cost of sale — which is appropriate for subscription DTC models and is how several analysts now model it — the gross margin improvement is 3–5 points, not 8–12. The assumption is not flagged in the initiative brief." },
        { name: 'Synthesizer', text: 'Confidence: Probable that DTC expansion improves gross margin. Contested on the magnitude — 3–5 points is defensible; 8–12 points requires the CAC classification assumption and a brand repositioning effect that this initiative does not include. Recommendation: restate the initiative forecast with a 3–7 point range and make the CAC classification assumption explicit.' },
        { name: 'Contrarian — Unresolved objection', text: '"The margin cases cited involve brand repositioning, not channel-only shifts. This initiative does not include a product mix change. Applying repositioning-era margin data to a channel-only expansion will systematically overstate the outcome."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested on magnitude', accent: true },
        { key: 'Confidence', val: '91%' },
        { key: 'Key assumption', val: 'CAC classification as marketing vs. COGS — 2× difference in outcome' },
        { key: 'Recommendation', val: 'Restate as 3–7 point range; disclose CAC classification assumption' },
      ],
      unresolvedObjection: '"The margin cases cited involve brand repositioning, not channel-only shifts. Applying repositioning-era margin data to a channel-only expansion will systematically overstate the outcome."',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 02 of 03 · Enterprise',
      name: 'The M&A Integration Risk Assessment',
      persona: 'VP Corporate Development · Global Technology Company',
      question: '"What does the post-merger integration literature establish about the probability of achieving the stated $400M synergy target within 24 months, and where is the risk most concentrated?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }],
      agentBlocks: [
        { name: 'Methodologist', text: 'Synergy composition analysis: the $400M breaks down as $180M cost synergies (facilities, headcount) and $220M revenue synergies (cross-sell). Historical data: cost synergies realise at approximately 80% of target within 24 months; revenue synergies realise at approximately 35% of target in the same window. Applied to this deal: expected realisation = ($180M × 0.80) + ($220M × 0.35) = $221M. The gap to target is $179M.' },
        { name: 'Pragmatist', text: 'Two integration priorities based on disaggregated analysis: (1) Front-load geographic expansion synergies — highest probability of realisation, least integration complexity. (2) Treat product bundling synergies as a 36-month target, not 24-month — revise board reporting accordingly to avoid miss-vs.-target framing in Q6–Q8.' },
        { name: 'Synthesizer', text: 'Board presentation updated to show disaggregated synergy realisation curves by category, with cost synergies on 24-month timeline and revenue synergies on 36-month timeline. Point estimate replaced with probability-weighted range.' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — $221M probable vs. $400M target', accent: true },
        { key: 'Guardian', val: '93%' },
        { key: 'Key gap', val: 'Revenue synergies: 35% 24-month realisation rate vs. 80% for cost synergies' },
        { key: 'Board reframe', val: 'Disaggregated curves: cost (24m) + revenue (36m) — not single point estimate' },
      ],
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 03 of 03 · Enterprise',
      name: 'The Operational Excellence Benchmark',
      persona: 'COO · Global Logistics Company',
      question: '"What does the evidence show about the operational leverage achievable from last-mile delivery route optimisation AI, and how do published efficiency gains compare to vendor claims?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }],
      agentBlocks: [
        { name: 'Guardian SVS', text: '14 citations reviewed. Three vendor white papers cited as independent evidence were produced by the same vendor group whose product is being evaluated. Flagged Critical — removed from evidence base. Without vendor white papers, independent peer-reviewed evidence supports 8–11% cost reduction, not the 15–22% in the proposal.' },
        { name: 'Contrarian', text: '"The methodologist is correct on additionality, but 3–6% incremental improvement on a $2.4B annual delivery cost base is $72–144M. At a 3-year payback the investment is still justifiable even with the corrected estimate. The problem is that the vendor\'s claims were evaluated against the wrong baseline, and the procurement team needs to renegotiate performance guarantees against the marginal improvement standard."' },
        { name: 'Pragmatist', text: 'Vendor performance guarantees renegotiated against marginal improvement baseline (vs. existing route optimisation system) rather than unoptimised baseline. Contract SLAs updated to reflect independently evidenced 3–6% improvement range.' },
      ],
      output: [
        { key: 'Finding', val: 'Probable at 3–6% marginal gain', accent: true },
        { key: 'Guardian', val: '92%' },
        { key: 'SVS flag', val: 'Critical — 3 vendor white papers removed from evidence base' },
        { key: 'Contract action', val: 'Renegotiate guarantees against marginal (not absolute) improvement baseline' },
      ],
      sessionLink: '/outcomes',
    },
  ],
  relatedCards: [
    { eyebrow: 'Solutions page', name: 'Enterprise', desc: 'The full solutions page for this vertical — problem framing, configuration panel, and why Augle for enterprise strategy.', href: '/solutions/enterprise' },
    { eyebrow: 'Related hub', name: 'Venture capital + PE hub', desc: 'Investment thesis reviews, TAM validation, and portfolio company stress tests — adjacent patterns for corporate development.', href: '/use-cases/venture-capital' },
    { eyebrow: 'Related hub', name: 'Financial services hub', desc: 'Equity research reviews and risk model validation — adjacent patterns for corporate finance functions.', href: '/use-cases/financial-services' },
  ],
  ctaTitle: 'Run a real session<br>on your question.',
  ctaBody: 'Join the waitlist and get one Standard session free — real deliberation, not a simulation.',
  ctaSolutionHref: '/solutions/enterprise',
  ctaSolutionLabel: 'Enterprise solutions page',
};

export const HEALTHCARE_HUB: HubData = {
  slug: 'healthcare', activeSlug: 'healthcare',
  breadcrumbLabel: 'Healthcare + life sciences',
  eyebrow: 'Use cases · Healthcare + life sciences',
  heroTitle: 'Three sessions.<br>One <em class="italic text-terracotta">vertical.</em>',
  heroBody: 'How the ensemble serves medical affairs teams, HTA analysts, and clinical research directors — reviewing clinical evidence to the standard it will face from regulators, payers, and ERG reviewers.',
  heroLinks: ['CMOs reviewing AI-assisted clinical tool adoption evidence', 'P&T committees comparing formulary treatment pathway options', 'Clinical development VPs reviewing Phase 2b trial design', 'Medical affairs directors preparing HTA submissions'],
  panelRows: [
    { label: 'Sessions', value: '3 hypothetical' },
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Depths', value: 'Standard · Deep' },
    { label: 'Guardian mode', value: 'Clinical integrity', accent: true },
    { label: 'Common outputs', value: 'Contested clinical findings · population scope flags · trial design risks' },
    { label: 'Solutions page', value: 'Healthcare', link: '/solutions/healthcare' },
  ],
  sessions: [
    {
      num: 'Session 01 of 03 · Healthcare + life sciences',
      name: 'The Clinical Evidence Review',
      persona: 'Chief Medical Officer · Regional Health System',
      question: '"Does the published evidence support adopting AI-assisted colonoscopy detection as standard of care, and what are the unresolved safety and efficacy questions before system-wide rollout?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Clinical integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Methodologist', text: 'Surrogate endpoint problem: all major CADe trials use ADR as the primary endpoint. ADR is a validated surrogate for colonoscopy quality but not a direct measure of cancer prevention. The FDA approved CADe devices based on ADR improvement alone. Whether ADR improvement from AI assistance confers the same cancer prevention benefit as ADR improvement from other quality interventions is not established.' },
        { name: 'Synthesizer', text: 'Confidence: Probable that CADe improves ADR. Contested whether ADR improvement prevents cancer at population scale. Gap on overdiagnosis and diminutive lesion removal risk. Clinical recommendation: pilot with post-polypectomy complication monitoring and 3-year interval cancer tracking before system-wide rollout.' },
        { name: 'Contrarian — Unresolved objection', text: '"AI detection optimised for sensitivity increases detection of diminutive lesions with low malignant potential. One health system saw post-polypectomy bleeding increase 23% without reduced interval cancers after system-wide CADe adoption. This safety signal requires prospective monitoring before rollout."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — safety monitoring required', accent: true },
        { key: 'Confidence', val: '41%' },
        { key: 'Guardian', val: 'Clinical integrity' },
        { key: 'Clinical action', val: 'Pilot with post-polypectomy complication monitoring before system-wide rollout' },
      ],
      unresolvedObjection: '"AI detection optimised for sensitivity increases detection of diminutive lesions with low malignant potential. One health system saw post-polypectomy bleeding increase 23% without reduced interval cancers after system-wide CADe adoption."',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 02 of 03 · Healthcare + life sciences',
      name: 'The Formulary Decision Brief',
      persona: 'Pharmacy & Therapeutics Committee · Academic Medical Centre',
      question: '"What does the evidence base establish about the comparative effectiveness of GLP-1 agonists vs. bariatric surgery for long-term weight maintenance in patients with BMI 35–40, and what does the formulary decision need to account for?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Clinical integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Methodologist', text: 'Comparison validity: head-to-head RCT data comparing GLP-1 to surgery does not exist. Available evidence is observational or indirect comparison. The populations in surgery trials and GLP-1 trials differ systematically in comorbidity burden, which confounds any indirect comparison. A formulary decision that treats indirect comparison evidence as equivalent to RCT evidence will be methodologically contested.' },
        { name: 'Pragmatist', text: 'Formulary framing: present this as a treatment pathway decision, not a cost comparison. For BMI 35–40 without metabolic comorbidity: GLP-1 trial with explicit discontinuation protocol. For BMI 35–40 with comorbidity (T2D, hypertension): surgery referral pathway with GLP-1 as bridge. Document decision criteria explicitly so the P&T committee can revisit when 5-year GLP-1 maintenance data is available.' },
        { name: 'Contrarian — Reopen condition', text: '"5-year GLP-1 maintenance data with discontinuation arm available. At that point the formulary decision can be grounded in matched-duration outcome comparison rather than indirect evidence."' },
      ],
      output: [
        { key: 'Finding', val: 'Gap — no head-to-head RCT exists', accent: true },
        { key: 'Guardian', val: '96% · Clinical integrity' },
        { key: 'Formulary decision', val: 'Treatment pathway by comorbidity profile — not single formulary position' },
        { key: 'Reopen condition', val: '5-year GLP-1 maintenance data with discontinuation arm' },
      ],
      reopenCondition: '5-year GLP-1 maintenance data with discontinuation arm available. At that point the formulary decision can be grounded in matched-duration outcome comparison rather than indirect evidence.',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 03 of 03 · Healthcare + life sciences',
      name: 'The Trial Design Review',
      persona: 'VP Clinical Development · Mid-size Biotech',
      question: '"Does our Phase 2b oncology study meet the evidentiary standards that FDA will require for accelerated approval consideration, and where are the protocol weaknesses?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Clinical integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Methodologist', text: "Type I error inflation risk: the proposed design uses three interim analyses with alpha spending allocated equally across interim looks. FDA's recent feedback in analogous trials has indicated preference for O'Brien-Fleming or Lan-DeMets alpha spending, not equal allocation. Equal allocation inflates Type I error at early interim analyses when sample sizes are small. This is a protocol weakness that will appear in FDA pre-submission feedback." },
        { name: 'Pragmatist', text: "Protocol strength: adaptive design is generally sound. Two pre-submission requirements: (1) switch to O'Brien-Fleming alpha spending or provide statistical justification for equal allocation. (2) Request pre-IND meeting specifically on biomarker endpoint acceptability as primary before finalising the SAP." },
        { name: 'Contrarian — Unresolved objection', text: '"FDA has not accepted the proposed biomarker as a primary endpoint for accelerated approval in this tumour type. This requires pre-IND meeting resolution before the statistical analysis plan is finalised. Proceeding without FDA feedback on this point risks a complete response letter on the primary endpoint."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — protocol has material weaknesses', accent: true },
        { key: 'Guardian', val: 'Clinical integrity' },
        { key: 'Key risk 1', val: 'Equal alpha spending → Type I error inflation at early interims' },
        { key: 'Key risk 2', val: 'Biomarker endpoint not accepted by FDA for this tumour type — requires pre-IND meeting' },
      ],
      unresolvedObjection: '"FDA has not accepted the proposed biomarker as a primary endpoint for accelerated approval in this tumour type. This requires pre-IND meeting resolution before the statistical analysis plan is finalised."',
      sessionLink: '/outcomes',
    },
  ],
  relatedCards: [
    { eyebrow: 'Solutions page', name: 'Healthcare + life sciences', desc: 'The full solutions page for this vertical — problem framing, configuration panel, and why Augle for clinical evidence review.', href: '/solutions/healthcare' },
    { eyebrow: 'Related hub', name: 'Research labs hub', desc: 'Replication reviews, technology readiness assessments, and competitive intelligence — adjacent patterns for pharma R&D.', href: '/use-cases/research-labs' },
    { eyebrow: 'Related hub', name: 'Law firms hub', desc: 'Expert witness preparation and regulatory enforcement preview — adjacent patterns for life sciences legal matters.', href: '/use-cases/law-firms' },
  ],
  ctaTitle: 'Run a real session<br>on your question.',
  ctaBody: 'Join the waitlist and get one Standard session free — real deliberation, not a simulation.',
  ctaSolutionHref: '/solutions/healthcare',
  ctaSolutionLabel: 'Healthcare solutions page',
};

export const GOVERNMENT_HUB: HubData = {
  slug: 'government', activeSlug: 'government',
  breadcrumbLabel: 'Government',
  eyebrow: 'Use cases · Government + public sector',
  heroTitle: 'Three sessions.<br>One <em class="italic text-terracotta">vertical.</em>',
  heroBody: 'How the ensemble serves civil servants, policy teams, and legal advisors — reviewing business cases, ministerial briefs, and decision records to the standard of NAO scrutiny, parliamentary committees, and judicial review.',
  heroLinks: ['Deputy secretaries reviewing programme business cases pre-Treasury', 'Heads of analysis stress-testing ministerial briefings pre-committee', 'Chief procurement officers assessing major IT programme risk', 'Senior analysts preparing intelligence assessments with appropriate uncertainty'],
  panelRows: [
    { label: 'Sessions', value: '3 hypothetical' },
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Depths', value: 'Standard · Deep' },
    { label: 'Guardian mode', value: 'Editorial / Policy integrity', accent: true },
    { label: 'Common outputs', value: 'NAO-ready evidence · committee preparation items · procurement risk flags' },
    { label: 'Solutions page', value: 'Government', link: '/solutions/government' },
  ],
  sessions: [
    {
      num: 'Session 01 of 03 · Government',
      name: 'The Programme Evaluation Brief',
      persona: 'Deputy Secretary, Department of Labour',
      question: '"What does the evidence base establish about the effectiveness of apprenticeship programmes in improving long-term earnings outcomes for participants, and does the current programme design match what the literature shows works?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Editorial integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Methodologist', text: "Selection bias concern: quasi-experimental designs in this literature use comparison groups of workers who applied to apprenticeships but were not accepted. This comparison group may differ systematically from participants on unobservable motivation and employer quality dimensions. The earnings premium estimate could partially reflect employer quality selection rather than human capital development. No instrumental variable study has cleanly resolved this." },
        { name: 'Synthesizer', text: 'Confidence: Probable that the programme produces positive earnings outcomes. Contested on magnitude due to selection bias. Gap on design feature evidence. Programme recommendation: commission a randomised expansion study with design feature variation to establish causal mechanism before the next reauthorisation cycle.' },
        { name: 'Contrarian — Unresolved objection', text: '"The programme operates above the 2:1 mentor ratio threshold that the mentorship quality literature identifies as the quality inflection point. 60% of registered sites are above this threshold. The programme design does not match what the evidence shows works."' },
      ],
      output: [
        { key: 'Finding', val: 'Probable — contested on design match', accent: true },
        { key: 'Guardian', val: '90% · Editorial integrity' },
        { key: 'Key gap', val: '60% of sites above mentor ratio quality threshold' },
        { key: 'Action', val: 'Commission randomised expansion study with design feature variation' },
      ],
      unresolvedObjection: '"The programme operates above the 2:1 mentor ratio threshold that the mentorship quality literature identifies as the quality inflection point. 60% of registered sites are above this threshold. The programme design does not match what the evidence shows works."',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 02 of 03 · Government',
      name: 'The Procurement Risk Assessment',
      persona: 'Chief Procurement Officer, Department of Defense',
      question: '"What does the evidence on large-scale government IT procurement outcomes show about the probability of on-time, on-budget delivery for a cloud migration programme of this scale, and where is risk most concentrated?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }],
      agentBlocks: [
        { name: 'Cartographer', text: 'Base rate calibration: the $2.1B programme falls in the >$1B government IT category. GAO historical data for this category: 23% delivered on time and on budget; 47% delivered with >50% cost overrun; 30% cancelled or restructured. Applying base rates, expected cost at completion: $2.8–3.4B. Expected timeline: 18–36 months beyond current projection.' },
        { name: 'Pragmatist', text: 'Three risk concentration points based on programme-specific analysis: (1) Requirements lock — 60% of DoD IT overruns originate from requirements changes after contract award. (2) Contractor concentration — single prime contractor model creates single point of failure. (3) Security clearance pipeline — cleared personnel bottleneck is the leading cause of schedule slippage. Address all three in programme governance before contract award.' },
        { name: 'Synthesizer', text: 'DoD-specific post-2020 cloud programme base rates compiled and substituted for GAO aggregate. Risk concentration assessment updated with programme-specific requirements lock and clearance pipeline analysis.' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — 23% on-time/budget base rate', accent: true },
        { key: 'Guardian', val: '94%' },
        { key: 'Expected cost', val: '$2.8–3.4B vs. $2.1B budgeted (GAO base rate)' },
        { key: 'Risk concentration', val: 'Requirements lock · contractor concentration · clearance pipeline' },
      ],
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 03 of 03 · Government',
      name: 'The Inter-Agency Intelligence Brief',
      persona: 'Senior Analyst, National Security Council',
      question: '"What does the open-source evidence establish about the state of adversary AI compute acquisition and what are the key uncertainties in the current intelligence assessment?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Deep', variant: 'deep' }, { label: 'Editorial integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Methodologist', text: 'Indicator reliability: the current assessment relies on three open-source indicator categories: (1) research publication citations of specific compute resources, (2) satellite imagery of data centre construction, and (3) semiconductor import partner data. Each has known limitations. Research citations undercount classified and non-published work. Satellite imagery has 6–9 month latency. Import data captures official channels, not grey market.' },
        { name: 'Synthesizer', text: 'Confidence: Contested. Assessment should be presented as a range with explicit uncertainty bounds rather than a point estimate. The three-indicator methodology cannot distinguish low capability from sophisticated evasion at current signal strength. Recommendation: flag this epistemic limitation explicitly in the NSC brief and recommend augmented collection to resolve the ambiguity.' },
        { name: 'Contrarian — Unresolved objection', text: '"Absence of signal across all three indicator categories is consistent with both low capability and sophisticated evasion. The assessment cannot distinguish between these hypotheses on open-source evidence alone. This epistemic limitation must be explicitly stated in the NSC brief."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — cannot distinguish capability from evasion', accent: true },
        { key: 'Guardian', val: '96% · Editorial integrity' },
        { key: 'Key uncertainty', val: 'Three-indicator methodology cannot distinguish low capability from evasion' },
        { key: 'Brief requirement', val: 'Explicit epistemic limitation statement — range not point estimate' },
      ],
      unresolvedObjection: '"Absence of signal across all three indicator categories is consistent with both low capability and sophisticated evasion. The assessment cannot distinguish between these hypotheses on open-source evidence alone."',
      sessionLink: '/outcomes',
    },
  ],
  relatedCards: [
    { eyebrow: 'Solutions page', name: 'Government + public sector', desc: 'The full solutions page for this vertical — problem framing, configuration panel, and why Augle for government evidence work.', href: '/solutions/government' },
    { eyebrow: 'Related hub', name: 'Policy + lawmakers hub', desc: 'Regulatory impact reviews, bill scoring, and public health mandate analysis — adjacent patterns for legislative teams.', href: '/use-cases/policy' },
    { eyebrow: 'Related hub', name: 'Law firms hub', desc: 'Judicial review risk assessments and regulatory enforcement previews — adjacent patterns for government legal work.', href: '/use-cases/law-firms' },
  ],
  ctaTitle: 'Run a real session<br>on your question.',
  ctaBody: 'Join the waitlist and get one Standard session free — real deliberation, not a simulation.',
  ctaSolutionHref: '/solutions/government',
  ctaSolutionLabel: 'Government solutions page',
};

export const FINANCIAL_SERVICES_HUB: HubData = {
  slug: 'financial-services', activeSlug: 'financial-services',
  breadcrumbLabel: 'Financial services',
  eyebrow: 'Use cases · Financial services',
  heroTitle: 'Three sessions.<br>One <em class="italic text-terracotta">vertical.</em>',
  heroBody: 'How the ensemble serves compliance teams, research analysts, and risk functions — stress-testing compliance positions, equity research reports, and risk model assumptions before the regulator does.',
  heroLinks: ['CROs reviewing credit risk model performance in new rate environments', 'Fixed income heads calibrating rates strategy against historical cycles', 'CCOs assessing AI surveillance programme exam probability', 'Research analysts stress-testing investment thesis before publication'],
  panelRows: [
    { label: 'Sessions', value: '3 hypothetical' },
    { label: 'Mode', value: 'Letters & Science · Prediction Markets' },
    { label: 'Depths', value: 'Standard · Deep' },
    { label: 'Guardian mode', value: 'Financial integrity', accent: true },
    { label: 'Common outputs', value: 'Compliance gaps · model blind spots · exam probability estimates' },
    { label: 'Solutions page', value: 'Financial services', link: '/solutions/financial-services' },
  ],
  sessions: [
    {
      num: 'Session 01 of 03 · Financial services',
      name: 'The Credit Risk Model Validation',
      persona: 'Chief Risk Officer · Regional Bank',
      question: '"Does the evidence support the assumption that the incumbent credit scoring model maintains predictive validity in the current macroeconomic environment, and where are the model\'s blind spots?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Financial integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Methodologist', text: 'Temporal sampling problem: the model was trained in a prolonged low-rate, low-default environment. Consumer behaviour in high-rate environments (debt service ratio management, strategic default decisions) is governed by different factors than low-rate behaviour. A model trained on 2010–2019 data has never seen a consumer population making decisions under 7%+ mortgage rates and 22%+ revolving credit rates simultaneously.' },
        { name: 'Synthesizer', text: 'Confidence: Contested on model validity. The phantom accuracy objection is methodologically serious and unresolved. Recommendation: commission a reject inference study using a random sample of declined applications approved for monitoring purposes before next regulatory model validation.' },
        { name: 'Contrarian — Unresolved objection', text: '"Validation on approved portfolios cannot detect systematic miscalibration in the declined population. The model may be generating phantom accuracy by declining creditworthy borrowers at scale in the new rate environment. Reject inference study required before next regulatory validation."' },
      ],
      output: [
        { key: 'Finding', val: 'Contested — out-of-sample risk unresolved', accent: true },
        { key: 'Confidence', val: '34%' },
        { key: 'Guardian', val: 'Financial integrity' },
        { key: 'Regulatory action', val: 'Reject inference study before next PRA model validation cycle' },
      ],
      unresolvedObjection: '"Validation on approved portfolios cannot detect systematic miscalibration in the declined population. The model may be generating phantom accuracy by declining creditworthy borrowers at scale in the new rate environment."',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 02 of 03 · Financial services',
      name: 'The Rates Strategy Review',
      persona: 'Head of Fixed Income, Asset Management · PIMCO',
      question: '"What does the historical evidence on Fed pivot cycles establish about forward curve accuracy at 18 months, and how should this inform our current positioning?"',
      tags: [{ label: 'Prediction Markets', variant: 'markets' }, { label: 'Deep', variant: 'deep' }],
      agentBlocks: [
        { name: 'Cartographer', text: 'Forecasting accuracy calibration: across the four documented peak cycles, 18-month forward curves overestimated the terminal rate by an average of 180 basis points. Applied to current pricing: if the pattern holds, the market is pricing in 180bps too much persistence. The Contrarian should be asked specifically whether fiscal dominance changes this calibration.' },
        { name: 'Synthesizer', text: 'Prediction Markets calibration: historical prior suggests 18-month forward curve overstates by ~180bps. Fiscal dominance discount suggested by Contrarian: 50%. Probability-weighted adjustment: ~90bps. Current positioning implication: duration extension is warranted but less aggressive than pure historical base rates suggest. Present as a range (60–120bps adjustment) given model uncertainty.' },
        { name: 'Contrarian — Unresolved objection', text: '"Published empirical study on forward curve accuracy at 18 months in high-deficit (>5% GDP) rate peak environments does not exist. Current evidence base does not include a direct analogue to the current fiscal context."' },
      ],
      output: [
        { key: 'Finding', val: 'Probable — 60–120bps duration extension warranted', accent: true },
        { key: 'Guardian', val: '93% · Financial integrity' },
        { key: 'Key uncertainty', val: 'No historical analogue for current fiscal dominance context' },
        { key: 'Positioning', val: 'Duration extension — less aggressive than pure historical base rates imply' },
      ],
      reopenCondition: 'Published empirical study on forward curve accuracy at 18 months in high-deficit (>5% GDP) rate peak environments.',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 03 of 03 · Financial services',
      name: 'The Compliance Risk Brief',
      persona: 'Chief Compliance Officer · Global Investment Bank',
      question: '"Based on current regulatory signals, what is the probability that our current AI-assisted trading surveillance programme will face a material exam finding in the next 18 months?"',
      tags: [{ label: 'Prediction Markets', variant: 'markets' }, { label: 'Standard', variant: 'standard' }, { label: 'Financial integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Cartographer', text: "Regulatory signal analysis: in the two prior cases where SEC/FINRA issued joint exam priority letters for specific technology categories (algorithmic trading, 2019; digital assets, 2021), formal findings followed in 60–70% of examinations within 18 months of the priority letter publication. Current programme has three documentation gaps relative to the guidance in the 2024 exam priority letter." },
        { name: 'Pragmatist', text: 'Three pre-exam actions: (1) Close the three documentation gaps identified in the 2024 priority letter within 60 days — these are the lowest-hanging fruit and the most likely exam focus. (2) Commission a mock examination specifically on AI surveillance governance. (3) Brief the Board Audit Committee on the exam probability before the next scheduled exam notification.' },
        { name: 'Synthesizer', text: 'Three documentation gaps closed and mock examination completed. At that point re-run exam probability estimate against the revised documentation posture.' },
      ],
      output: [
        { key: 'Finding', val: 'Probable — 60–70% material finding risk', accent: true },
        { key: 'Guardian', val: '96% · Financial integrity' },
        { key: 'Documentation gaps', val: '3 gaps vs. 2024 exam priority letter — exam focus' },
        { key: 'Pre-exam actions', val: '3 specific actions to reduce exam probability before notification' },
      ],
      sessionLink: '/outcomes',
    },
  ],
  relatedCards: [
    { eyebrow: 'Solutions page', name: 'Financial services', desc: 'The full solutions page for this vertical — problem framing, configuration panel, and why Augle for financial services.', href: '/solutions/financial-services' },
    { eyebrow: 'Related hub', name: 'Law firms hub', desc: 'Regulatory enforcement preview and expert witness preparation — adjacent patterns for financial services legal matters.', href: '/use-cases/law-firms' },
    { eyebrow: 'Related hub', name: 'Venture capital + PE hub', desc: 'Portfolio company stress tests and investment thesis reviews — adjacent patterns for financial decision-making.', href: '/use-cases/venture-capital' },
  ],
  ctaTitle: 'Run a real session<br>on your question.',
  ctaBody: 'Join the waitlist and get one Standard session free — real deliberation, not a simulation.',
  ctaSolutionHref: '/solutions/financial-services',
  ctaSolutionLabel: 'Financial services solutions page',
};

export const MEDIA_HUB: HubData = {
  slug: 'media', activeSlug: 'media',
  breadcrumbLabel: 'Media + journalism',
  eyebrow: 'Use cases · Media + journalism',
  heroTitle: 'Three sessions.<br>One <em class="italic text-terracotta">vertical.</em>',
  heroBody: 'How the ensemble serves investigative reporters, science editors, and data journalists — stress-testing evidence, statistical claims, and source independence before publication enters the public record.',
  heroLinks: ['Senior editors reviewing pre-publication investigative claims', 'Research directors auditing misinformation source dynamics', 'Business correspondents verifying earnings story accounting claims', 'Science editors fact-checking research translation for public audiences'],
  panelRows: [
    { label: 'Sessions', value: '3 hypothetical' },
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Depths', value: 'Standard · Deep' },
    { label: 'Guardian mode', value: 'Editorial / Financial integrity', accent: true },
    { label: 'Common outputs', value: 'Pre-publication edits · source independence flags · legal vulnerability assessment' },
    { label: 'Solutions page', value: 'Media', link: '/solutions/media' },
  ],
  sessions: [
    {
      num: 'Session 01 of 03 · Media + journalism',
      name: 'The Pre-Publication Fact Review',
      persona: 'Senior Editor, Investigations · ProPublica',
      question: '"Does the evidence cited in this investigative piece support the causal claim that the hospital\'s billing algorithm systematically disadvantaged low-income patients, and will the claim survive legal and factual challenge?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Editorial integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Guardian SVS', text: '28 citations and data sources verified. Two of the three outcome studies cited used data provided by a patient advocacy group that has previously filed a complaint against this specific hospital. Not independent. Flagged Moderate — disclosed. One statistical comparison uses unadjusted outcome rates; the comorbidity adjustment would likely reduce the stated disparity by 30–40%.' },
        { name: 'Synthesizer', text: 'Editorial recommendation: the systematic disparity in billing terms is documented and publishable. The causal outcome claim requires comorbidity-adjusted data before publication. Two-track approach: publish the billing terms story now (solid evidentiary ground) and hold the causal outcome claim for the follow-up piece once adjusted data is obtained.' },
        { name: 'Contrarian — Unresolved objection', text: '"The headline causal claim is not supported by the cited evidence without comorbidity adjustment. The adjusted disparity may be 30–40% smaller. The billing terms disparity is publishable; the causal outcome claim should be held pending adjusted analysis."' },
      ],
      output: [
        { key: 'Finding', val: 'Billing terms: Probable · Causal claim: Contested', accent: true },
        { key: 'Dissent', val: '1 Strong (Unresolved)' },
        { key: 'Guardian', val: 'Editorial integrity' },
        { key: 'Editorial action', val: 'Publish billing terms story now; hold causal claim pending comorbidity-adjusted analysis' },
      ],
      unresolvedObjection: '"The headline causal claim is not supported by the cited evidence without comorbidity adjustment. The adjusted disparity may be 30–40% smaller. The billing terms disparity is publishable; the causal outcome claim should be held."',
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 02 of 03 · Media + journalism',
      name: 'The Misinformation Source Audit',
      persona: 'Research Director, Digital Journalism · The Atlantic',
      question: '"What does the evidence establish about the origin and spread dynamics of the specific climate misinformation narrative under investigation, and which claims are documentably false vs. contested?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Editorial integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Synthesizer', text: 'Falsity classification: three distinct claims in the narrative require separate treatment. (1) "Arctic ice is recovering" — documentably false; contradicted by 30-year NSIDC dataset. (2) "NSIDC data shows recovery" — documentably false; NSIDC explicitly corrected this characterisation. (3) "Warming trend is reversing" — Contested; contested by the scientific consensus but involves a predictive claim about trend continuation that requires care in characterisation.' },
        { name: 'Pragmatist', text: 'Editorial framing recommendation: distinguish between "scientifically contested" (genuine scientific debate) and "contradicted by overwhelming consensus with minority dissent." Claim (3) falls in the latter category. This distinction is both editorially accurate and legally more defensible than characterising a consensus position as merely contested.' },
        { name: 'Contrarian', text: '"Claim (3) framing revised from \'contested\' to \'contradicted by overwhelming consensus with minority dissent\' with explicit IPCC confidence level citation. This framing is both more accurate and more legally defensible." — objection resolved by reframe.' },
      ],
      output: [
        { key: 'Claims 1 & 2', val: 'Documentably false', accent: true },
        { key: 'Claim 3', val: 'Consensus-contradicted — not merely contested' },
        { key: 'Guardian', val: '93% · Editorial integrity' },
        { key: 'Editorial framing', val: 'Distinguish documentably false from consensus-contradicted in publication' },
      ],
      sessionLink: '/outcomes',
    },
    {
      num: 'Session 03 of 03 · Media + journalism',
      name: 'The Earnings Story Verification',
      persona: 'Business Correspondent · Financial Times',
      question: '"Does the evidence support the claim in the draft story that the company\'s EBITDA margin improvement is primarily driven by accounting reclassification rather than operational improvement, and what will IR pushback?"',
      tags: [{ label: 'Letters & Science', variant: 'ls' }, { label: 'Standard', variant: 'standard' }, { label: 'Financial integrity', variant: 'guardian' }],
      agentBlocks: [
        { name: 'Guardian SVS', text: '12 financial filings and analyst reports verified. One analyst report cited as independent validation of the margin improvement was issued by a bank with a buy rating and active banking relationship with the company. Flagged Moderate — retained with disclosure.' },
        { name: 'Contrarian', text: '"The reclassification is non-standard but not unique — at least six S&P 500 companies use similar SBC presentation. IR will argue the company is moving toward what they will describe as industry practice. The story needs to address whether this is an isolated practice or part of a broader trend of EBITDA presentation that systematically obscures SBC cost. The larger story may be more important than the individual company."' },
        { name: 'Synthesizer', text: '"IR response obtained and addressed. If IR argues the reclassification is industry practice, broaden the story to include comparable SBC reclassification analysis across peer set before publication."' },
      ],
      output: [
        { key: 'Finding', val: 'Probable — reclassification documented', accent: true },
        { key: 'Guardian', val: '95% · Financial integrity' },
        { key: 'IR pushback', val: '"Industry practice" — broaden to peer set if IR makes this argument' },
        { key: 'Story development', val: 'Peer set SBC reclassification analysis may be the larger story' },
      ],
      sessionLink: '/outcomes',
    },
  ],
  relatedCards: [
    { eyebrow: 'Solutions page', name: 'Media + journalism', desc: 'The full solutions page for this vertical — problem framing, configuration panel, and why Augle for journalism.', href: '/solutions/media' },
    { eyebrow: 'Related hub', name: 'Think tanks + nonprofits hub', desc: 'Pre-publication evidence reviews and advocacy position stress-testing — adjacent patterns for research journalism.', href: '/use-cases/think-tanks' },
    { eyebrow: 'Related hub', name: 'Financial services hub', desc: 'Equity research reviews and compliance risk briefs — adjacent patterns for business and financial journalism.', href: '/use-cases/financial-services' },
  ],
  ctaTitle: 'Run a real session<br>on your question.',
  ctaBody: 'Join the waitlist and get one Standard session free — real deliberation, not a simulation.',
  ctaSolutionHref: '/solutions/media',
  ctaSolutionLabel: 'Media solutions page',
};
