import SolutionLayout, { VerticalData } from '../SolutionLayout';

const data: VerticalData = {
  slug: 'policy', activeSlug: 'policy',
  breadcrumbLabel: 'Policy + lawmakers',
  eyebrow: 'Solutions · Policy + lawmakers',
  heroTitle: 'Find the objection<br>before the opposition<br><em class="italic text-terracotta">does.</em>',
  heroBody: 'Policy is made on evidence that is contested, incomplete, or misrepresented — and the consequences of getting it wrong are public. Augle runs the adversarial review that a well-resourced opposition will run anyway, before the decision is made rather than after.',
  personas: [
    'Policy analysts reviewing legislative evidence bases',
    'Parliamentary researchers preparing briefings',
    'Regulatory teams assessing impact methodology',
    'Think tank researchers producing policy recommendations',
  ],
  panelLabel: 'Session configuration · Policy',
  panelRows: [
    { label: 'Mode', value: 'Letters & Science' },
    { label: 'Guardian', value: 'Policy integrity', accent: true },
    { label: 'Depth', value: 'Standard · Deep' },
    { label: 'Doc ingestion', value: 'Bills · RIAs · Studies · Briefings' },
    { label: 'SVS checks', value: 'Retraction DB · statutory version · jurisdiction scope' },
    { label: 'Output', value: 'Evidence-anchored finding · confidence grade · dissent flags · audit trail' },
  ],
  problemTitle: 'The objection your<br>opponents have<br>already found.',
  problemBody: 'A well-resourced opposition research team works with the same evidence you do. The question is whether they find the weakness in your cost-benefit methodology, your behavioural evidence base, or your legal citations before you do — or whether you find it first and close it.',
  problemQuestions: [
    '"Does our CBA methodology account for distributional effects the committee will ask about?"',
    '"Which of our evidence citations will the opposition\'s research team challenge first?"',
    '"Is the behavioural evidence at national scale or only in constrained trial contexts?"',
    '"Are our legal citations current law or have they been distinguished?"',
  ],
  problemItems: [
    { title: 'Cost-benefit methodologies that don\'t survive scrutiny', body: 'The Methodologist evaluates whether your CBA methodology actually supports the claims your policy recommendation makes. Discount rate choices, time horizon assumptions, and distributional weighting decisions all have legitimate methodological objections — Augle surfaces them before the committee does.' },
    { title: 'Behavioural evidence that doesn\'t replicate at scale', body: 'Behavioural interventions tested in controlled or localised settings frequently don\'t replicate when applied nationally. The Contrarian specifically targets external validity — whether the evidence base supports the scale of deployment the policy assumes.' },
    { title: 'Legal citations with jurisdiction or version problems', body: 'Legal integrity mode checks statutory references against current law — outdated statutory versions, jurisdiction mismatches, and superseded regulations are flagged before they enter a submission or briefing.' },
    { title: 'The objection your opponents have already found', body: 'The Contrarian is calibrated to surface the adversarial framing a well-resourced opposition team will deploy. Unresolved objections appear verbatim with resolution conditions. The policy team that knows these going in controls the hearing.' },
  ],
  useCasesTitle: 'Three sessions.<br>Three moments before publication.',
  useCasesBody: 'Each scenario is drawn from the Augle Use Case Compendium — hypothetical sessions illustrating deliberation behaviour at critical policy decision points.',
  useCases: [
    {
      num: 'Use case 01 of 03 · Policy + lawmakers',
      name: 'The Infrastructure Bill Review',
      persona: 'Senior Policy Analyst, Treasury · Pre-committee scrutiny',
      badge: 'Standard depth · document ingestion', badgeVariant: 'standard',
      question: '"Does the proposed infrastructure bill\'s cost-benefit methodology adequately account for climate-adjusted risk over a 30-year horizon?"',
      highlights: [
        { agent: 'Cartographer', text: 'Settled: CBA frameworks exist and are applied. Contested: whether the discount rate (3.5%) is appropriate for climate-adjusted projections beyond 15 years. Unknown: the quantified exposure under three warming scenarios.' },
        { agent: 'Methodologist', text: 'Construct validity: the discount rate choice is methodologically disputed for climate-adjusted long-horizon projections — the Stern Review and subsequent literature supports lower rates. This is a known, named dispute, not a speculative one.' },
        { agent: 'Contrarian', text: 'Strong objection (Unresolved): "The committee has already briefed a Stern Review expert. The 3.5% discount rate for a 30-year climate-adjusted analysis is the first thing the Treasury Select Committee will challenge. The sensitivity analysis doesn\'t address the rate choice — it addresses the cost estimates."' },
        { agent: 'Pragmatist', text: 'Add a climate-adjusted discount rate sensitivity analysis at 2.5% and 1.5% — showing the BCR range. This doesn\'t change the recommendation; it demonstrates methodological awareness of the dispute and pre-empts the committee\'s question.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Contested — defensible for near-term projections; inadequate for 30-year climate-adjusted claims as presented' },
        { key: 'Key objection', val: 'Discount rate choice for climate-adjusted long-horizon CBA — named, active academic dispute' },
        { key: 'SVS', val: 'All cited studies verified. No retracted papers.' },
        { key: 'Next step', val: 'Add sensitivity analysis at 1.5% and 2.5% discount rate — completable in one day before committee date' },
      ]},
      value: 'The team knew the discount rate was a potential weakness. They didn\'t know the committee had already briefed a Stern Review expert. They found that out from Augle — before the session, not during it.',
    },
    {
      num: 'Use case 02 of 03 · Policy + lawmakers',
      name: 'The Behavioural Intervention Assessment',
      persona: 'Regulatory Impact Analyst · Department for Health and Social Care',
      badge: 'Standard depth', badgeVariant: 'standard',
      question: '"Is the behavioural evidence base for the proposed sugar levy sufficient to support the projected public health outcomes at national scale?"',
      highlights: [
        { agent: 'Cartographer', text: 'Settled: sugar taxation reduces consumption in trial contexts. Contested: whether consumption reduction translates to health outcome improvement at national scale, and whether reformulation replaces consumption reduction. Unknown: distributional effects on lower-income households at proposed levy rate.' },
        { agent: 'Methodologist', text: 'External validity gap: all supporting studies used localised or controlled interventions. The RIA projects national-scale health outcomes without evidence of national-scale effect. This is a construct validity issue — the evidence supports a claim smaller than the one being made.' },
        { agent: 'Contrarian', text: 'Moderate objection: "The distributional effect on lower-income households at the proposed levy rate is not in the RIA. The Health Select Committee\'s written evidence will include this — it\'s in the published literature and the opposition has it."' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Probable at reduced scope — consumption reduction is probable; health outcome projection at national scale is not supported at the claimed confidence level' },
        { key: 'Key gap', val: 'Distributional analysis for lower-income households absent from RIA — committee will raise it' },
        { key: 'Next step', val: 'Commission distributional modelling and reframe health outcome projections to match evidentiary scope' },
      ]},
      value: 'The distributional objection wasn\'t in the RIA. It would have been in the Health Select Committee\'s written evidence within 48 hours of publication. Three weeks of additional modelling prevented a headline they couldn\'t walk back.',
    },
    {
      num: 'Use case 03 of 03 · Policy + lawmakers',
      name: 'The Crime Reduction Briefing',
      persona: 'Parliamentary Researcher · Home Affairs Committee preparation',
      badge: 'Rapid · orientation', badgeVariant: 'standard',
      question: '"Does the evidence on neighbourhood policing support the claimed relationship between officer presence and crime reduction?"',
      highlights: [
        { agent: 'Cartographer', text: 'Settled: officer presence correlates with reduced recorded crime in some contexts. Contested: whether the effect is displacement vs. net reduction. Unknown: the replication record for the specific neighbourhood policing model referenced in the briefing.' },
        { agent: 'Contrarian', text: 'Moderate objection: "The briefing conflates localised deterrence with net crime reduction — the displacement literature is directly relevant and not addressed."' },
        { agent: 'Synthesizer', text: 'Probable for localised deterrence effects. Contested for net crime reduction claims at neighbourhood level. The briefing\'s framing overstates the evidence.' },
      ],
      outcome: { label: 'Session output', rows: [
        { key: 'Finding', val: 'Contested at the claim level stated in the briefing — displacement not addressed' },
        { key: 'Unresolved objection', val: 'Displacement literature directly relevant to net reduction claim — not in current briefing' },
        { key: 'Edit needed', val: 'Add one paragraph scoping claim to localised deterrence, noting the displacement debate' },
      ]},
      value: 'A briefing that conflates localised deterrence with net crime reduction is a briefing that gets corrected in committee — publicly, and by the opposition researcher who already knows the distinction. It got fixed before it was published.',
    },
  ],
  howTitle: 'Built for the policy<br>evidence lifecycle.',
  howSteps: [
    { n: 1, title: 'Submit your policy question and upload documents', body: 'Upload the bill, RIA, or briefing pack alongside your research question. The Topic Architect sets the Guardian to policy integrity mode and configures the ensemble for policy evidence evaluation.' },
    { n: 2, title: 'The Guardian validates statutory references and sources', body: 'Legal integrity mode cross-references every statutory citation against current law — outdated versions, jurisdiction mismatches, and superseded regulations are flagged. Source independence and retraction status are checked for every cited study.' },
    { n: 3, title: 'The Contrarian plays the opposition researcher', body: 'The Contrarian is specifically calibrated to surface the adversarial framing a well-resourced opposition team, a select committee researcher, or a hostile think tank will deploy. Unresolved objections appear verbatim with resolution conditions.' },
    { n: 4, title: 'You get the finding — and the specific edits needed', body: 'The Pragmatist translates unresolved objections into concrete pre-publication actions — sensitivity analyses to add, claims to scope, distributional analyses to commission. You leave with a specific list, not general uncertainty.' },
  ],
  configLabel: 'Policy integrity mode · Guardian configuration',
  configRows: [
    { key: 'Statutory check', val: 'Every statutory citation checked against current law — outdated versions, jurisdiction mismatches, and superseded regulations flagged' },
    { key: 'Retraction check', val: 'Every cited study cross-referenced against retraction databases before entering the evidence registry' },
    { key: 'Preprint flag', val: 'Preprint sources flagged SVS_UNVERIFIED — evidence node capped at Probable' },
    { key: 'Source independence', val: 'Concentration of evidence from single source, funder, or institution flagged for confirmation bias risk' },
    { key: 'Scale validity', val: 'Evidence from controlled or localised contexts flagged when used to support national-scale projections' },
    { key: 'Audit trail', val: 'Full session record exportable — SVS log, objection register, confidence grades, Pragmatist actions' },
  ],
  whyTitle: 'What makes it different<br>from a desk review.',
  whyCards: [
    { title: 'Finds the objection before the opposition does', body: 'The Contrarian is designed to surface the adversarial framing that a well-resourced opposition team will deploy. It steelmans every claim before challenging it — which means it finds the strongest version of the objection, not a weak one you can dismiss.' },
    { title: 'Validates every source automatically', body: "The Guardian's Source Verification Service authenticates every citation before it enters the evidence base — retraction status, statutory version, and jurisdiction scope. A briefing built on a superseded statutory reference is a briefing that gets corrected in committee." },
    { title: 'Produces an auditable evidence record', body: 'The full deliberation record — evidence nodes, objections, confidence grades, Guardian flags — is exportable. For evidence-based policy, the audit trail is as valuable as the finding.' },
    { title: 'Scales from rapid orientation to deep adversarial review', body: 'Rapid mode gives you an evidence landscape in minutes. Standard runs the full ensemble. Deep adds the flagship Contrarian for the highest-stakes submissions. Choose the depth the decision warrants.' },
    { title: 'Names the objection precisely', body: 'Every unresolved Contrarian objection includes a resolution condition — specifically what evidence, analysis, or framing would close it. "Uncertainty exists" is not an acceptable objection format. The condition gives you exactly what to add to the briefing.' },
    { title: '$0.60 per Standard session', body: 'A Standard deliberation costs $0.60. The select committee hearing it would have to answer in costs considerably more. The economics of running Augle before publication are straightforward.' },
  ],
  ctaTitle: 'Find the objection<br>before the committee does.',
  ctaBody: 'Join the waitlist and get one Standard session free. Run it on a real policy question before your next deadline.',
};

export default function PolicyPage() { return <SolutionLayout v={data} />; }
